# maps_amaranth_grids.py -- ASCII map data for maps_amaranth.py.
#
# Reverse-extracted 27 Aug 2026 from the shipped src/data/mapsAmaranth.ts --
# NOT hand-authored, NOT the original design source (none survives). See
# maps_amaranth.py's own RECONSTRUCTION NOTE for the full story of why.
#
# Kept in its own file purely because 36 grids make maps_amaranth.py itself
# hard to read past all the data -- same reason maps.py keeps its four
# grids as plain top-of-file constants would have been fine at that size,
# but 14,280 tiles across 36 maps is a different scale of file. Edit these
# ASCII strings directly, then re-run maps_amaranth.py.

# Reverse-extracted 27 Aug 2026 from src/data/mapsAmaranth.ts (the only surviving
# source -- see the RECONSTRUCTION NOTE at the top of this file). Dict preserves
# the live file's own declaration order (Act I -> II -> III).
GRIDS = {
    "map_amaranth_muster": {
        # Mission rework pass (8 Sep 2026):
        # rubble islands at (6-7,4),(11-12,4),(6-7,6),(11-12,6) so the field
        # has cover on the way to the road and the pocket has corners to fight
        # from.
        "name": 'Muster — Thistledown Watch',
        "const": "MUSTER_TILES",
        "w": 20, "h": 12,
        "ascii": [
            '^^,,...........,,,^^',
            '^,,..##........,,,,^',
            ',,...##..........,,,',
            'P..=============..,,',
            'PP.==.%%...%%.==..E,',
            'P..==.%%..##..==..,,',
            'PP.==.%%...%%.==..E,',
            'P..==.%%..##..==..,,',
            ',,...##..........E,,',
            '^,,..##........,,,,^',
            '^^,,...........,,,^^',
            '^^^,,.........,,,^^^',
        ],
    },
    "map_amaranth_wire_and_mud": {
        "name": 'Wire and Mud — the Listening Post',
        "const": "WIRE_AND_MUD_TILES",
        "w": 22, "h": 11,
        "ascii": [
            '^^,,.............,,^^^',
            ',,..................,,',
            ',,....BBBBBB........,,',
            'P.....BHHHHB........,,',
            'PP....BHHHHB........,,',
            'P......HHHHBE.......,,',
            'PP....BHHHHBE.......,,',
            'P.....BHHHHB........,,',
            ',,....BBBBBB........,,',
            ',,..................,,',
            '^^,,.............,,^^^',
        ],
    },
    "map_amaranth_the_low_ground": {
        "name": 'The Low Ground',
        "const": "THE_LOW_GROUND_TILES",
        "w": 24, "h": 15,
        "ascii": [
            '^^^^,,........,,,,^^^^^^',
            '^^^,,,..........,,,,^^^^',
            '^,,,..............,,,,,^',
            'P,,.....................',
            'P....~~.....~~..........',
            'P..~~~~~...~~~~......E..',
            'P...~~~~~~~~~~~.........',
            'P..~~~~~~~~~~~~~.....E..',
            'P...~~~~~~~~~~~.........',
            'P...~~~~~~~~~........E..',
            ',,...~~~~~~~............',
            ',,,....~~~..............',
            ',,,,...................,',
            '^,,,,.................,,',
            '^^^,,,,............,,,^^',
        ],
    },
    "map_amaranth_tunnel_rats": {
        "name": 'Tunnel Rats',
        "const": "TUNNEL_RATS_TILES",
        "w": 30, "h": 19,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^^^^,,........,,,,^^^^^^^^^^^^',
            '^^,,,,........,,,,,,^^^^^^^^^^',
            ',,,,%%%%,,,%%%%,,.............',
            ',,,,%.........%,,.............',
            'P,,,%.........%,,.............',
            'P,,,%.........%,,.............',
            'P,,,%.........%,,.............',
            'P,,,%...EE....%,,......E......',
            'P,,,%.........%,,.............',
            'P,,,%.........%,,.............',
            'P,,,%.........%,,.............',
            ',,,,%.........%,,.............',
            ',,,,%%%%,,,%%%%,,.............',
            '^^,,,,........,,,,,,^^^^^^^^^^',
            '^^^^,,........,,,,^^^^^^^^^^^^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_foraging_party": {
        # Mission rework pass (8 Sep 2026):
        # a sump column at x=17 (rows 1-4 and 7-11) with the seams moved to
        # (18,3)/(18,9) and the exits shuffled to x=20-21: the extraction now
        # runs through a two-tile gap the Bloom can cork (Gallcyst in the gap,
        # its first appearance, earlier than the story's Mission 9) instead of
        # an open field the target strolls across. Rubble at (9,3)/(9,9) for
        # the escort.
        "name": 'Foraging Party',
        "const": "FORAGING_PARTY_TILES",
        "w": 22, "h": 13,
        "ascii": [
            '^^^,,,,,,,,,,,,,,,,^^^',
            '^^^..............w.^^^',
            ',................w...,',
            ',........%.......wE..,',
            'P........%%......w...X',
            'PP.......%%.........XX',
            'P..........##.......X.',
            'PP.........##....w..XX',
            'P........%%......w...X',
            ',........%.......wE..,',
            ',................w...,',
            '^^^..............w.^^^',
            '^^^,,,,,,,,,,,,,,,,^^^',
        ],
    },
    "map_amaranth_house_colors": {
        "name": 'House Colors',
        "const": "HOUSE_COLORS_TILES",
        "w": 20, "h": 12,
        "ascii": [
            ',,,,,,,,,,,,,,,,,,,,',
            ',........B.........,',
            ',........B.........,',
            ',......##B.##......,',
            'P......##B.##..E...,',
            'PP===============E==',
            'P================E==',
            'P......##B.##..E...,',
            ',......##B.##......,',
            ',........B.........,',
            ',........B.........,',
            ',,,,,,,,,,,,,,,,,,,,',
        ],
    },
    "map_amaranth_sporewatch_ridge": {
        "name": 'Sporewatch Ridge',
        "const": "SPOREWATCH_RIDGE_TILES",
        "w": 20, "h": 12,
        "ascii": [
            ',,,,,,,,PPPP,,,,,,,,',
            ',.......PPPP.......,',
            ',..................,',
            ',......^^^^^^......,',
            ',......^HHHH^......,',
            ',......^HHHH^......,',
            ',......^HHHH^......,',
            ',......^^^^^^......,',
            ',....,,,,,,,,,,....,',
            ',....,,,,,,,,,,....,',
            ',..................,',
            ',,,,,,,,EEEE,,,,,,,,',
        ],
    },
    "map_amaranth_the_choir_sings": {
        "name": 'The Choir Sings',
        "const": "THE_CHOIR_SINGS_TILES",
        "w": 22, "h": 13,
        "ascii": [
            '^^^^,,,,,,,,,,,,,,^^^^',
            '^^^^..............^^^^',
            '^^^^..............^^^^',
            ',....................,',
            ',...................E,',
            'P................EE..,',
            'PP...............EE..,',
            'PP...............EE..,',
            'P........~~~~........,',
            ',........~~~~.......E,',
            '^^^^..............^^^^',
            '^^^^..............^^^^',
            '^^^^,,,,,,,,,,,,,,^^^^',
        ],
    },
    "map_amaranth_cut_off": {
        "name": 'Cut Off',
        "const": "CUT_OFF_TILES",
        "w": 22, "h": 14,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,,,,,,,,,,,,,,,,,',
            ',,....E...E...E.....,,',
            ',,..................,,',
            ',,......E...........,,',
            ',,.PP....##...^^....,,',
            ',,.PP....##%%.^^...E,,',
            ',,.P.....%%%%.^^....,,',
            ',,.......%%...^^...E,,',
            ',,...........E......,,',
            ',,...wwwwwwwwwwwww..,,',
            ',,...wwwwwwwwwwwww..,,',
            ',,,,,,,,,,,,,,,,,,,,,,',
            '^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_amaranth_betrayal": {
        # Mission rework pass (8 Sep 2026):
        # the extraction is a walled compound (x=18-22, rows 2-10) with doors
        # at (18,3) and (18,9) and the exit tiles inside it: the collaborators
        # hold a building, not a field edge. Seams pulled back to
        # (8,2)/(16,2)/(8,10).
        "name": 'The Amaranth Betrayal',
        "const": "THE_AMARANTH_BETRAYAL_TILES",
        "w": 24, "h": 13,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,,,,,,,,,,,,,,,,,,,',
            ',,......E.......E.BBBBB,',
            ',,.................XXXB,',
            ',,........##......BXXXB,',
            ',,.PP.....##......B...B,',
            ',,.PP....=======..B...B,',
            ',,.P......##......B...B,',
            ',,........##......BXXXB,',
            ',,...........~~~~..XXXB,',
            ',,......E....~~~~.BBBBB,',
            ',,,,,,,,,,,,,,,,,,,,,,,,',
            '^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_long_walk_back": {
        # Mission rework pass (8 Sep 2026):
        # the ridge column at x=6-7 is sump from row 0 to 12 except rows 5-7:
        # one three-tile gap between Lask and the pads, which the Undertow
        # cork. Ridge is passable at cost 2, so ridge alone never made a wall
        # — traced: Lask walked around it.
        "name": 'The Long Walk Back',
        "const": "THE_LONG_WALK_BACK_TILES",
        "w": 34, "h": 13,
        "ascii": [
            '^^^^^^ww^^^^^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,ww,,,,,,,,,,,,,,,,,,,,,,,,,,',
            ',,....ww....www......E..........,,',
            ',,....ww....www....%%.......E...,,',
            ',,....ww....www....%%.....%%....,,',
            ',,XX.......E===...........%%.PP.,,',
            ',,XX........===...........%%.PP.,,',
            ',,X.........===E..........%%.P..,,',
            ',,....ww....www.......%%..%%....,,',
            ',,....ww....www.......%%....E...,,',
            ',,....ww....www......E..........,,',
            ',,,,,,ww,,,,,,,,,,,,,,,,,,,,,,,,,,',
            '^^^^^^ww^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_fallow_line": {
        "name": 'The Fallow Line — Thistledown Watch',
        "const": "THE_FALLOW_LINE_TILES",
        "w": 26, "h": 14,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,',
            ',,.......E...E...E......,,',
            ',,......................,,',
            ',,......%%........%%....,,',
            ',,......%%.^^^^^^.%%...E,,',
            ',,.PP...%%.^HHHH^.%%....,,',
            ',,.PP...%%.^HHHH^.%%....,,',
            ',,.P....%%.^^^^^^.%%...E,,',
            ',,......%%........%%....,,',
            ',,......................,,',
            ',,.......E...E...E......,,',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_new_colors": {
        # Mission rework pass (8 Sep 2026):
        # a bloom mat at (20-22,6-7) beside the east seam for the
        # clear_bloom_patch bonus objective.
        "name": 'New Colors — The Muster Ground',
        "const": "NEW_COLORS_TILES",
        "w": 26, "h": 14,
        "ascii": [
            ',,,,,,,,,,####,,,,,%%%%,,,',
            ',,,,,,,,,,####,,,,,%%%%,,,',
            '..........................',
            'P............======.......',
            'P...........^======....EE.',
            'P..,........^.............',
            'P..,........^.......~~~...',
            'P..,........^.......~~~...',
            'P..,........^.............',
            'P...........^======....EE.',
            'P............======.......',
            '..........................',
            ',,,,,,,,,,####,,,,,%%%%,,,',
            ',,,,,,,,,,####,,,,,%%%%,,,',
        ],
    },
    "map_amaranth_steel_rain": {
        "name": 'Steel Rain',
        "const": "STEEL_RAIN_TILES",
        "w": 28, "h": 16,
        "ascii": [
            '~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
            '~~%%~~~~%%~~~~~~%%~~~~%%~~~~',
            '..%%....%%......%%....%%....',
            'P...........................',
            'P...%%.............%%...EE..',
            'P...%%.............%%.......',
            'P...........................',
            'P.......................E...',
            'P........................E..',
            'P...........................',
            'P...%%.............%%.......',
            '....%%.............%%...EE..',
            '............................',
            '..%%....%%......%%....%%....',
            '~~%%~~~~%%~~~~~~%%~~~~%%~~~~',
            '~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
        ],
    },
    "map_amaranth_landfall": {
        "name": 'Landfall',
        "const": "LANDFALL_TILES",
        "w": 24, "h": 14,
        "ascii": [
            'ww,.....##......##......',
            'ww,.....##......##......',
            'ww,P..........E.........',
            'ww,P...E................',
            'ww,P...............E....',
            'ww,P....................',
            'ww,P....................',
            'ww,P....................',
            'ww,P....................',
            'ww,P...............E....',
            'ww,P...E................',
            'ww,P..........E.........',
            'ww,.....##......##......',
            'ww,.....##......##......',
        ],
    },
    "map_amaranth_collaborators": {
        "name": 'Collaborators',
        "const": "COLLABORATORS_TILES",
        "w": 24, "h": 14,
        "ascii": [
            ',,,,,,####,,,,####,,,,,,',
            ',,,,,,####,,,,####,,,,,,',
            '........................',
            'P...%%.............%%.E.',
            'P...%%......####...%%...',
            'P.......................',
            'P.....................E.',
            'P.....................E.',
            'P.......................',
            'P...%%......####...%%...',
            'P...%%.............%%.E.',
            '........................',
            ',,,,,,####,,,,####,,,,,,',
            ',,,,,,####,,,,####,,,,,,',
        ],
    },
    "map_amaranth_wellroot": {
        # Mission rework pass (8 Sep 2026):
        # rebuilt as three walled tiers (walls at rows 4 and 9, gaps at
        # (22-23,4) and (5-6,9)) with the pads at (2-4,1-3), seams at
        # (20,2)/(21,7)/(20,11) and the exits at (1-2,12)/(1-3,13): the way to
        # Solheim is down through two gaps and the way out is the same two
        # gaps with the Bloom behind you.
        "name": 'The Wellroot Uncovered',
        "const": "WELLROOT_TILES",
        "w": 28, "h": 15,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B,PPP,,,,,,,,,,,,,,,,,,,,,,B',
            'B,PPP,,,,,,,,,,,,,,,E,,,,,,B',
            'B,PPP,,,,,,,,,,,,,,,,,,,,,,B',
            'BBBBBBBBBBBBBBBBBBBBBB,,BBBB',
            'B,,,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,~~~,,,,,,,,,,,,B',
            'B,,,,,,,,,,,~~~,,,,,,E,,,,,B',
            'B,,,,,,,,,,,,~,,,,,,,,,,,,,B',
            'BBBBB,,BBBBBBBBBBBBBBBBBBBBB',
            'B,,,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,E,,,,,,B',
            'BXX,,,,,,,,,,,,,,,,,,,,,,,,B',
            'BXXX,,,,,,,,,,,,,,,,,,,,,,,B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_dravens_cut": {
        "name": "Draven's Cut",
        "const": "DRAVENS_CUT_TILES",
        "w": 32, "h": 14,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'B..............................B',
            'B.E...........%%%%...........E.B',
            'B.E...........PPPP...........E.B',
            'B.E...........PPPP...........E.B',
            'B.E...........%%%%...........E.B',
            'B..............................B',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_silent_ward": {
        "name": 'The Silent Ward',
        "const": "SILENT_WARD_TILES",
        "w": 26, "h": 16,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B%%%%%%%%%%%%%%%%%%%%%%%%B',
            'B%#######%%%%%%%%#######%B',
            'B%#PPP###%%%%%%%%#######%B',
            'B%#PPP###%%%%%%%%###E###%B',
            'B%#PPP###%%%%%%%%#######%B',
            'B%#######%%%%%%%%#######%B',
            'B%%%%%%%%%##E###%%%%%%%%%B',
            'B%%%%%%%%%######%%%%%%%%%B',
            'B%#######%%%%%%%%#######%B',
            'B%#######%%%%%%%%#######%B',
            'B%###E###%%%%%%%%###E###%B',
            'B%#######%%%%%%%%#######%B',
            'B%#######%%%%%%%%#######%B',
            'B%%%%%%%%%%%%%%%%%%%%%%%%B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_marrows_line": {
        "name": "Marrow's Line",
        "const": "MARROWS_LINE_TILES",
        "w": 26, "h": 14,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B,,,,,,,,,,,^^,,,,,,,,,,,B',
            'B,P,,,,,,,,,^^,,,,,,,,,,,B',
            'B,P,,,%%,,,,^^,,,,%%,,,,,B',
            'B,P,,,%%,,,,^^,,,,%%,,,E,B',
            'B,P,,,,,,,,,,,,,,,,,,,,,,B',
            'B,P,,,,,,,,,,,,,,,,,,,,,,B',
            'B,P,,,,,,,,,,,,,,,,,,,,E,B',
            'B,P,,,,,,,,,,,,,,,,,,,,,,B',
            'B,P,,,%%,,,,^^,,,,%%,,,,,B',
            'B,P,,,%%,,,,^^,,,,%%,,,E,B',
            'B,,,,,,,,,,,^^,,,,,,,,,,,B',
            'B,,,,,,,,,,,^^,,,,,,,,,,,B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_cut_the_root": {
        "name": 'Cut the Root',
        "const": "CUT_THE_ROOT_TILES",
        "w": 26, "h": 15,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,,,B',
            'BPPPP,,,,,,,,%,,,,,,,,,,,B',
            'BPPPP,,,%%,,,,,,,,,,#####B',
            'BPPPP,,,,,,,,,,,,,,,E####B',
            'BPPPP,,,,,,,,,,,,%,,#####B',
            'BPPPP,,,,,,,,,,,,,,,##E##B',
            'BPPPP,,,,,,,,,,,,%,,#####B',
            'BPPPP,,,,,,,,,,,,,,,####EB',
            'BPPPP,,,%%,,,,,,,,,,#####B',
            'BPPPP,,,,,,,,%,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,,,B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_ash_on_the_water": {
        "name": 'Ash on the Water',
        "const": "ASH_ON_THE_WATER_TILES",
        "w": 28, "h": 14,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B.....wwwwwwwwwwwwwww......B',
            'B.....wwwwwwwwwwwwwwPP.....B',
            'B.E...==============PPDDDD.B',
            'B.....==============PPDDDD.B',
            'B.....wwwwwwwwwwwwwwPPDDDD.B',
            'B.....wwwwwwwwwwwwwwPPDDDD.B',
            'B.....wwwwwwwwwwwwwwPPDDDD.B',
            'B.....wwwwwwwwwwwwwwPPDDDD.B',
            'B.....==============PPDDDD.B',
            'B.E...==============PPDDDD.B',
            'B.....wwwwwwwwwwwwwwPP.....B',
            'B.....wwwwwwwwwwwwwww......B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_the_amaranth_accord": {
        # Mission rework pass (8 Sep 2026):
        # a wall column at x=19 (gaps at (19,2) and (19,10)) between the field
        # and the extraction block, seams moved to (23,2) and the gap mouths:
        # the last walk to the tree line goes through one of two doors the
        # Accord's own people are standing in.
        "name": 'The Amaranth Accord',
        "const": "THE_AMARANTH_ACCORD_TILES",
        "w": 26, "h": 13,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B,,,,,,,,,,,,,,,,,,B,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,E,B',
            'B,,,,,,,,##,,,,,,,,BXXXXXB',
            'BPPP,,,,,#,,,,,,,,,BXXXXXB',
            'BPPP,,,,,,,,,,,,,,,BXXXXXB',
            'BPPP,,,,,,,,~~,,,,,BXXXXXB',
            'BPPP,,,,,,,,,,,,,,,BXXXXXB',
            'BPPP,,,,,,,,,,,#,,,BXXXXXB',
            'B,,,,,,,,,,,,,,##,,BXXXXXB',
            'B,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,B,,,,,B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_two_fires": {
        "name": 'Two Fires',
        "const": "TWO_FIRES_TILES",
        "w": 30, "h": 18,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B,,,,,E,,,,,E,,,,,E,,,,,E,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B,,,,,,,,,,,,,,,,,,,,,,,,,,,,B',
            'B............................B',
            'B............................B',
            'B............................B',
            'B............................B',
            'B.....%%.....PPPP.....%%.....B',
            'B............PPPP............B',
            'B............PPPP............B',
            'B............................B',
            'B............................B',
            'B............................B',
            'B############################B',
            'B############################B',
            'B#####E#####E#####E#####E####B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_the_reckoning": {
        "name": 'The Reckoning',
        "const": "THE_RECKONING_TILES",
        "w": 34, "h": 16,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,E,,,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,E,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,E,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,E,,,',
            'PPPP,,,,..................,,,,,,,,',
            'PPPP,,,,..................,,,,,,,,',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,E,,,,,',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_unnamed_beneath": {
        "name": 'The Unnamed Beneath',
        "const": "THE_UNNAMED_BENEATH_TILES",
        "w": 30, "h": 15,
        "ascii": [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
            'B%%%%%%%%%%%%%%%%%%%%%%%%%%%%B',
            'B%%%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'B%%%%%~~~E~~%%%%~~~E~~%%%%%%%B',
            'B%%%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'BPP%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'BPP........................XXB',
            'BPP........................XXB',
            'BPP........................XXB',
            'BPP%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'B%%%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'B%%%%%~~~E~~%%%%~~~E~~%%%%%%%B',
            'B%%%%%~~~~~~%%%%~~~~~~%%%%%%%B',
            'B%%%%%%%%%%%%%%%%%%%%%%%%%%%%B',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        ],
    },
    "map_amaranth_falling_back_to_meridian": {
        "name": 'Falling Back to Meridian',
        "const": "FALLING_BACK_TO_MERIDIAN_TILES",
        "w": 36, "h": 14,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',
            ',,,,,,,,,,,,,,,,,%%,,,,,,,%%,,,,,E,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,E,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,E,,',
            'PPPP,,HHHH,,,,,,,%%,,,,,,,%%,,,,,,,,',
            ',,,,,,,,,,,,,,,,,%%,,,,,,,%%,,,,,E,,',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_marrows_reckoning": {
        "name": "Marrow's Reckoning",
        "const": "MARROWS_RECKONING_TILES",
        "w": 28, "h": 15,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '............................',
            '.....................E......',
            '............................',
            'PPP.............%%......E...',
            'PPP.......%%....%%..........',
            'PPP.......%%....%%..........',
            'PPP.......%%....%%......E...',
            'PPP.......%%....%%..........',
            'PPP.......%%....%%..........',
            'PPP.............%%......E...',
            '............................',
            '.....................E......',
            '............................',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_outer_ring_falls": {
        "name": 'The Outer Ring Falls',
        # Mission rework pass (8 Sep 2026): the blockhouse's east wall is gone
        # (rows 5-8 at x=14 open). Sim-traced: with one west door the Bloom
        # queued single-file at it and the hold was a fortress (30/30 Hard
        # wins at under one mech down against 100+ hostiles); a matching
        # two-tile east door just moved the queue to the other side, with
        # a full-HP Choir plugging the doorway on a hold tile until the turn
        # limit (0/30). The east face is open now: the Bloom floods the box
        # instead of queuing at it, and the fight inside actually resolves.
        "const": "OUTER_RING_FALLS_TILES",
        "w": 30, "h": 16,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^............................^',
            '^...............,,%,.......EE^',
            '^...............,%,,.........^',
            '^........BBBBBB.%,,,.........^',
            '^.PPPP...BHHHH..,,,,.........^',
            '^.PPPP....HHHH..,,,%.........^',
            '^.PPPP....HHHH..,,%,........E^',
            '^.PPPP...BHHHH..,%,,........E^',
            '^........BBBBBB.%,,,.........^',
            '^...............,,,,.........^',
            '^...............,,,%.........^',
            '^...............,,%,.........^',
            '^...............,%,,.......EE^',
            '^............................^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_ashes_of_the_second_ring": {
        "name": 'Ashes of the Second Ring',
        "const": "ASHES_OF_THE_SECOND_RING_TILES",
        "w": 28, "h": 15,
        "ascii": [
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,',
            ',.####..####=%..####.####..,',
            ',.####..####=...####.####.E,',
            ',.####..####=...####.####..,',
            ',.....=====================,',
            ',PPPP.......=......%.......,',
            ',PPPP...####=...####.####EE,',
            ',PPPP..=####=...####.####..,',
            ',PPPP...####=...####.####EE,',
            ',...........=............%.,',
            ',.....=====================,',
            ',.####..####=...####.####..,',
            ',.####..####=...####.####.E,',
            ',.####..####=...####.####..,',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,',
        ],
    },
    "map_amaranth_the_last_convoy": {
        "name": 'The Last Convoy',
        "const": "THE_LAST_CONVOY_TILES",
        "w": 32, "h": 13,
        "ascii": [
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',
            ',.............EE........E......,',
            ',...%..#..%..#..%..#..%..#..%..,',
            ',..%..#..%..#..%..#..%..#..%...,',
            ',...................PPPP.......,',
            ',XX.=...=...=...=...PPPP=...=..,',
            ',XX=================PPPP=======,',
            ',XX.................PPPP.......,',
            ',..............................,',
            ',..%..#..%..#..%..#..%..#..%...,',
            ',.%..#..%..#..%..#..%..#..%..#.,',
            ',.............EE........E......,',
            ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',
        ],
    },
    "map_amaranth_hold_at_the_spire": {
        "name": 'Hold at the Spire',
        "const": "HOLD_AT_THE_SPIRE_TILES",
        "w": 26, "h": 16,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^..E.....E......E.....E..^',
            '^........%....#..........^',
            '^....%....#...........%..^',
            '^.....#...........%....#.^',
            '^.#...........%....#.....^',
            '^.........%....#.........^',
            '^.....%....#...........%.^',
            '^.%....#...........%.....^',
            '^..#...........%....#....^',
            '^.....PPPP......PPPP.....^',
            '^.....PPPP......PPPP.....^',
            '^.....DDDDDDDDDDDDDD.....^',
            '^.....DDDDDDDDDDDDDD.....^',
            '^.....DDDDDDDDDDDDDD.....^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_innermost_ring": {
        "name": 'The Innermost Ring',
        "const": "THE_INNERMOST_RING_TILES",
        "w": 28, "h": 16,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^.........,,...............^',
            '^...%%%%..........%%%%...E.^',
            '^..........................^',
            '^..........................^',
            '^.............BBBBBBB......^',
            '^.....PPPP....BHHHHHB......^',
            '^.....PPPP.....HHHHHB....E.^',
            '^.....PPPP.....HHHHHB......^',
            '^.....PPPP....BHHHHHB......^',
            '^.............BBBBBBB......^',
            '^..........................^',
            '^..........................^',
            '^...%%%%..........%%%%...E.^',
            '^.........,,...............^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_no_word_from_the_fleet": {
        "name": 'No Word from the Fleet',
        "const": "NO_WORD_FROM_THE_FLEET_TILES",
        "w": 26, "h": 16,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^...........EE...........^',
            '^.......%%......%%.......^',
            '^...##..............##...^',
            '^...##..............##...^',
            '^........................^',
            '^..........PPPP..........^',
            '^E,,.......PPPP.......,,E^',
            '^E,,.......PPPP.......,,E^',
            '^..........PPPP..........^',
            '^........................^',
            '^...##..............##...^',
            '^...##..............##...^',
            '^.......%%......%%.......^',
            '^...........EE...........^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_the_last_ring": {
        "name": 'The Last Ring',
        "const": "THE_LAST_RING_TILES",
        "w": 32, "h": 17,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^..............................^',
            '^..........,,..................^',
            '^...%%%%..............%%%%....E^',
            '^..............................^',
            '^..............................^',
            '^..............BBBBBBB.........^',
            '^.....PPPP.....BHHHHHB.........^',
            '^.....PPPP......HHHHHB........E^',
            '^.....PPPP......HHHHHB.........^',
            '^.....PPPP.....BHHHHHB.........^',
            '^..............BBBBBBB.........^',
            '^................B#B...........^',
            '^.................B............^',
            '^...%%%%..............%%%%....E^',
            '^..........,,..................^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
    "map_amaranth_until_relief": {
        "name": 'Until Relief',
        "const": "UNTIL_RELIEF_TILES",
        "w": 30, "h": 18,
        "ascii": [
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
            '^.............EE.............^',
            '^............%%%%............^',
            '^..E###................###E..^',
            '^...###................###...^',
            '^........%%........%%........^',
            '^............................^',
            '^...........PPPPPP...........^',
            '^E,,........PPPPPP........,,E^',
            '^E,,........PPPPPP........,,E^',
            '^...........PPPPPP...........^',
            '^............................^',
            '^........%%........%%........^',
            '^...###................###...^',
            '^..E###................###E..^',
            '^............%%%%............^',
            '^.............EE.............^',
            '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
        ],
    },
}
