# Mission rework specs — 8 Sep 2026 pass. Applied by apply_mission_rework.py (same folder).
# Source of truth for every mission's enemyWaves / spawn events / bonusObjective /
# objectiveParams overrides in src/data/campaignAmaranth.ts and campaignHouseAmaranth.ts.
# Edit here, re-run the apply script, never hand-edit the generated waves.
# Each note is the design intent in the game's voice plus what the sim said about earlier cuts.
# Ratings: claude/Bloom_Wars_Build_Log_Addendum_MissionRework_08Sep2026.md and ratings/ next to this file.
# Coordinates are (x, y). "E" = the map's spawn seams. See apply_rework.py's docstring.
W = "src/data/campaignAmaranth.ts"
H = "src/data/campaignHouseAmaranth.ts"

REWORK = {
  # ------------------------------------------------------------------ ACT I
  "AMARANTH_MISSION_1": {
    "file": W,
    "note": 'Muster. The sweep that stops being routine: the first drift comes down the road from the east, then the ridge gaps north and south open at turn 2 and the field is a pocket, not a front. Crawlmass only, twenty-two of them over four waves. (Twenty-five was 16% for the Hard bot at three mechs down a run — a G-tier squad kills one or two Crawlmass a turn and fifteen on the field at once buries it; eighteen was 30/30 at one down and twenty-one 29/30; twenty-three 10/30. The cliff is the turn-2 flank, which is the lesson. This is the tutorial; it should sting, not bury.)',
    "waves": [
      {"a": "bloom_crawlmass", "n": 7, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 4, "t": 2, "at": [(9, 0), (10, 0), (11, 0)]},
      {"a": "bloom_crawlmass", "n": 3, "t": 2, "at": [(9, 11), (10, 11), (11, 11)]},
      {"a": "bloom_crawlmass", "n": 5, "t": 4, "at": "E"},
      {"a": "bloom_crawlmass", "n": 3, "t": 6, "at": [(2, 0), (3, 11)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_2": {
    "file": W,
    "note": "Wire and Mud. One door, exactly as the briefing promises, and the movement in the wire is between the pads and that door: a pair already in the wire at 1, sporethrowers behind the pads at 2, a pack on the doorway's flanks at 3, the seams and more sporethrowers at 5, packs at 7 and 9. 'Six turns' is when the survey detail leaves, not when the Bloom does. (A first cut widened the door and ran the hold zone out through it; reverted, since the briefing and mapsAmaranth.test.ts both promise one door and a room five mechs can fill. A G-tier frame dies to four hits, so the opening pack is a pair: three in the squad's face at turn 1 was 0/30.)",
    "waves": [
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": [(4, 3), (4, 7)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 2, "at": [(2, 1), (2, 9)]},
      {"a": "bloom_splitfang", "n": 3, "t": 3, "at": [(5, 2), (5, 8)]},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 5, "at": [(4, 3), (4, 7)]},
      {"a": "bloom_splitfang", "n": 2, "t": 7, "at": [(4, 2), (4, 8)]},
      {"a": "bloom_splitfang", "n": 3, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_3": {
    "file": W,
    "note": "The Low Ground. The mat is the mission, and the Bloom keeps feeding it: the first drift is already on the far side, the sporethrowers are on the terrace behind the deploy line, and the seams push more crawlmass across the mat at turns 3, 5 and 7 — the Munti has to burn ground under fire, not after the fight, and the squad has to hold the mat's edge while he does.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": [(3, 4), (3, 6)]},
      {"a": "bloom_crawlmass", "n": 4, "t": 3, "at": [(15, 6), (15, 8)]},
      {"a": "bloom_splitfang", "n": 2, "t": 5, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 7, "at": [(15, 6), (15, 8)]},
      {"a": "bloom_splitfang", "n": 2, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_4": {
    "file": W,
    "note": 'Tunnel Rats. The ruin is a box with two doors, and the Undertow are under the floor of it. The surface Bloom outside is bait to pull the squad into the box; three burrowers surface once the squad is inside, and a second cell surfaces at turn 4 between the box and the pads so there is no clean way back out. (Four inside and three behind was 0/30 at F-tier: two Undertow surfacing on one frame is a kill, and Rourke walks back into the second cell.)',
    "waves": [
      {"a": "bloom_undertow", "n": 3, "t": 1, "at": [(7, 6), (11, 12), (11, 6)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 5, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 3, "at": "E"},
      {"a": "bloom_undertow", "n": 2, "t": 4, "at": [(2, 7), (2, 11)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": [(28, 4), (28, 14)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_5": {
    "file": W,
    "note": "Foraging Party. 'The gap' is now a real gap: a sump line at x=17 with a two-tile break at rows 5-6, the seams right behind it, the extraction beyond. Anand can't be shot, but she can be body-blocked — two Gallcyst have grown IN the gap (the door closing, literally — a sessile turret can't be lured off its tile the way a burrower can) with an Undertow behind them, so the squad has to cut the gap open under acid while a second drift arrives behind them at turn 3, sporethrowers take both ridges at 4, and more splitfang come through from the seams at 5. Turn limit 14 -> 10: the door really is closing. NOTE: the sim bot never attacks the cork (it focus-fires the weakest thing in sight), so its 0% here is a bot artifact — rated by trace: gap reached turn 4, 320 HP of Gallcyst cut in 2 squad turns, through by 8, out by 9-10. The downed pilot is south-centre, off the line of march.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 1, "t": 1, "at": [(17, 6)]},
      {"a": "bloom_undertow", "n": 1, "t": 1, "at": [(17, 5)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 3, "at": [(1, 2), (1, 10)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 4, "at": [(10, 1), (10, 11)]},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
    ],
    "events": [],
    "bonus": {"kind": "rescue_pilot", "at": (10, 10), "name": "Downed Pilot", "points": 40},
    "params": {'turnLimit': 11},
  },
  "AMARANTH_MISSION_6": {
    "file": W,
    "note": "House Colors. A checkpoint dispute is a firefight with a wall down the middle: a five-mech detachment with its own Munti holds the gate, the reserve comes up both flanking roads and the gate at turn 3, and two more arrive at turn 5 — ten regulars, not four. The first fight where the enemy takes cover and heals.",
    "waves": [
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 3, "at": [(18, 1)]},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 3, "at": [(18, 10)]},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 3, "at": "E"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 5, "at": "E"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 5, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },

  "AMARANTH_MISSION_7": {
    "file": W,
    "note": "Sporewatch Ridge. Hold the ridge, not the approach — and the approach is where the Undertow are: four burrowed on the slope the squad has to climb, surfacing under the first mech to cross. Sporethrowers lob from the south seams from turn 1, crawlmass flank in from both map edges at 2, the splitfang push lands at 4 and again at 6, and a last sporethrower line at 8 makes the ridge cost something every turn through 12. (One-unit cliff: this exact list is 36/50 for the Hard bot; one more Crawlmass on the turn-2 flank or one more Splitfang at 4 is 0/50. Every hostile on this map converges on the ring and on Rourke.)",
    "waves": [
      {"a": "bloom_sporethrower", "n": 1, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 2, "t": 1, "at": [(7, 8), (12, 8)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 3, "t": 2, "at": [(0, 5), (19, 5)]},
      {"a": "bloom_sporethrower", "n": 1, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 4, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_8": {
    "file": W,
    "note": "The Choir Sings. Dozens of voices, all one voice — so the Choir arrives in three voices: the first flight with its crawlmass screen from the east seams, a second flight over the north ridge at 3, a third over the south ridge at 5, and a splitfang pack up the middle at 6 to punish whoever scattered. Eight Choir. The ones who spread thinnest are the ones it converges on.",
    "waves": [
      {"a": "bloom_choir", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 1, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 3, "at": [(6, 0), (15, 0)]},
      {"a": "bloom_choir", "n": 2, "t": 5, "at": [(6, 12), (15, 12)]},
      {"a": "bloom_splitfang", "n": 3, "t": 6, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_9": {
    "file": W,
    "note": "Cut Off. Nobody's coming, and the Bloom knows it: a drift from the north seams, two Gallcyst already rooted in the ground the squad wants, a pack from the east at 2, sporethrowers walking in from the north at 3 to reach over the Tank, a bigger pack at 4, four Undertow surfacing around the habblock at 5, more packs and sporethrowers at 6, and everything at once at 8. Crawlmass are chaff to a D-tier Tank in cover — this one is mostly Splitfang. Ten turns.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_gallcyst", "n": 2, "t": 1, "at": [(8, 4), (13, 9)]},
      {"a": "bloom_splitfang", "n": 5, "t": 2, "at": [(19, 6), (19, 8)]},
      {"a": "bloom_sporethrower", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 3, "at": [(7, 5), (12, 5), (7, 9), (12, 8)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_undertow", "n": 3, "t": 5, "at": [(2, 4), (5, 8), (2, 8)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 5, "t": 6, "at": [(19, 6), (19, 8)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 7, "at": "E"},
      {"a": "bloom_crawlmass", "n": 6, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": {"kind": "rescue_pilot", "at": (7, 8), "name": "Downed Signals Officer", "points": 45},
  },
  "AMARANTH_MISSION_10": {
    "file": W,
    "note": "The Amaranth Betrayal. The east-face position House Amaranth ran from is a walled compound now, and the Bloom grew into it while it sat empty: a Gallcyst in each of its two doors, the extraction inside, four Undertow under the road between the squad and the compound. Drift and pack from all four seams at 1, the Bloom pouring out of the compound's own doors every two turns from 2 through 7, splitfang up behind the squad from the west at 4, sporethrowers on the flanks and the Choir over the north seams at 5 — the thing House Amaranth was actually watching for. Turn limit 14 -> 10: the clock is real but the pressure is the mission.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 2, "t": 1, "at": [(18, 3), (18, 9)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(9, 5), (12, 7), (14, 5), (11, 8)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 6, "t": 2, "at": [(17, 2), (17, 10)]},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": [(17, 2), (17, 10)]},
      {"a": "bloom_splitfang", "n": 5, "t": 4, "at": [(2, 3), (2, 9)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": [(17, 2), (17, 10)]},
      {"a": "bloom_sporethrower", "n": 3, "t": 5, "at": [(12, 2), (12, 10), (12, 1)]},
      {"a": "bloom_choir", "n": 3, "t": 5, "at": [(8, 2), (16, 2)]},
      {"a": "bloom_splitfang", "n": 4, "t": 7, "at": [(17, 2), (17, 10)]},
    ],
    "events": [],
    "bonus": "keep",
    "params": {"turnLimit": 10},
  },
  "AMARANTH_MISSION_11": {
    "file": W,
    "note": "The Long Walk Back. Twenty-seven tiles of ground the Line already lost once. The ridge columns at x=6-7 are sump now (rows 1-3, 9-11), so the road gate at rows 5-7 is the only way to the exit — and three Gallcyst have rooted in it. Undertow under the road, splitfang in the rubble pinch ahead, crawlmass on the road, a splitfang pack closing in behind from the east at 2 — faster than the Tank, which is the whole problem — sporethrowers on the sump lane at 3, a pack rising on the exit side of the gate at 5, and a pair of Choir behind at 6 for anyone still on the road. Turn limit 18 -> 9.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 3, "t": 1, "at": [(7, 5), (7, 6), (7, 7)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(18, 6), (23, 5), (23, 7), (10, 6)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": [(21, 2), (21, 10)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": [(11, 5), (15, 7)]},
      {"a": "bloom_splitfang", "n": 5, "t": 2, "at": [(28, 3), (28, 9)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 3, "at": [(14, 2), (14, 10)]},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": [(4, 3), (4, 9)]},
      {"a": "bloom_choir", "n": 2, "t": 6, "at": [(21, 2), (21, 10)]},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 11},
  },
  "AMARANTH_MISSION_12": {
    "file": W,
    "note": "The Fallow Line. Every side but the one you walked in from, and it doesn't stop: drift and pack at 1, splitfang at 3, the Choir at 4, more drift at 5, Sirenmaw at 6, a second Choir at 8, and the big push at 9 — the one that has to be on the ridge with you at turn 10. Hold from 10 to 16. Act I's last word.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 4, "at": "E"},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 6, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 8, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 9, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },

  # ------------------------------------------------------------------ ACT II
  "AMARANTH_MISSION_13": {
    "file": W,
    "note": "New Colors, Old Wounds. Ten mechs, simple ground — and the ground stops being simple at turn 2 when packs come in over both map edges, Undertow surface along the ridge line at 3, and the seams push again at 5 with the Choir behind at 7. A bloom patch between the road bands for whoever's Munti wants to prove something.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 5, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 5, "t": 2, "at": [(5, 1), (16, 1), (5, 12), (16, 12)]},
      {"a": "bloom_undertow", "n": 4, "t": 3, "at": [(11, 5), (11, 8), (13, 6), (13, 7)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": {"kind": "clear_bloom_patch", "tiles": [(20, 6), (21, 6), (22, 6), (20, 7), (21, 7), (22, 7)], "points": 50},
  },
  "AMARANTH_MISSION_14": {
    "file": W,
    "note": "Steel Rain. Providence's guns are live and the Bloom is already in the craters: two Gallcyst rooted mid-field, splitfang over the north mat at 2, Undertow under the rubble at 3, more splitfang over both mat edges at 4, the Choir at 5, Sirenmaw at 6, a second drift at 8. The mat along the north edge is the bonus — clear it under the guns.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_gallcyst", "n": 2, "t": 1, "at": [(12, 7), (15, 8)]},
      {"a": "bloom_splitfang", "n": 4, "t": 2, "at": [(8, 2), (16, 2)]},
      {"a": "bloom_undertow", "n": 5, "t": 3, "at": [(4, 4), (4, 10), (19, 4), (19, 10), (12, 6)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": [(8, 2), (16, 2), (8, 13), (16, 13)]},
      {"a": "bloom_choir", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 6, "at": "E"},
      {"a": "bloom_crawlmass", "n": 6, "t": 8, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 8, "at": "E"},
    ],
    "events": [],
    "bonus": {"kind": "clear_bloom_patch", "tiles": [(10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1)], "points": 50},
  },
  "AMARANTH_MISSION_15": {
    "file": W,
    "note": "Landfall. Under fire before your boots are down, and the beach is mined: the first wave is on top of the ramp at 1, Undertow surface under the sand at 2, the second wave lands at 3, Sirenmaw over both corners at 5, a last pack at 7. No grace turn.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 5, "t": 2, "at": [(5, 4), (5, 9), (6, 6), (5, 2), (5, 11)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 10, "t": 3, "at": "E"},
      {"a": "bloom_sporethrower", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 5, "t": 5, "at": [(20, 0), (20, 13)]},
      {"a": "bloom_splitfang", "n": 6, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_16": {
    "file": W,
    "note": "Collaborators. A garrison, not a patrol: seventeen conscripts and a House Amaranth medic hold the depot, six more conscripts come in off the flank roads at 3 — and from 5 the regulars arrive to stiffen them, four at 5 and two at 7 — the ones who volunteered. The surrendering conscript is on the west side; whether you go back for him is still your call.",
    "waves": [
      {"a": "hostile_mech_amaranth_conscript_01", "n": 5, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_conscript_02", "n": 4, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_conscript_03", "n": 4, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_conscript_04", "n": 4, "t": 1, "at": "E"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 1, "at": "E", "tier": "D"},
      {"a": "hostile_mech_amaranth_conscript_02", "n": 3, "t": 3, "at": [(3, 1), (11, 1)]},
      {"a": "hostile_mech_amaranth_conscript_04", "n": 3, "t": 3, "at": [(3, 12), (11, 12)]},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 7, "at": [(3, 12)], "tier": "D"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 7, "at": [(11, 1)], "tier": "D"},
    ],
    "events": [],
    "bonus": "keep",
  },
  "AMARANTH_MISSION_17": {
    "file": W,
    "note": "The Wellroot Uncovered. The terraces are three walled tiers now, and the only way down is the switchback: top tier east to the gap at x=22, middle tier west to the gap at x=5, then the extraction at the bottom tier's west end. About forty tiles for a Reeps — the Tank can't keep up, which is the decision. Each tier has its own seam feeding it, Undertow under the middle tier, and the root structure Static found is the mat on the way. Turn limit 16 -> 14. (Sim bot: 0% — its extraction target won't outrun the squad and the squad won't stop fighting the top seam; rated by trace: ~40 tiles at move 5 = 8 turns of walking plus two fights, 11-13 turns for a squad that keeps moving.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": [(20, 2)]},
      {"a": "bloom_sporethrower", "n": 3, "t": 1, "at": [(20, 2)]},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": [(21, 7)]},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(10, 6), (16, 6), (8, 8), (19, 8)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 6, "t": 4, "at": [(20, 11)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 4, "at": [(20, 11)]},
      {"a": "bloom_splitfang", "n": 4, "t": 6, "at": [(20, 2)]},
      {"a": "bloom_choir", "n": 3, "t": 7, "at": [(20, 11)]},
      {"a": "bloom_splitfang", "n": 4, "t": 9, "at": [(21, 7)]},
    ],
    "events": [],
    "bonus": {"kind": "clear_bloom_patch", "tiles": [(12, 6), (13, 6), (14, 6), (12, 7), (13, 7), (14, 7), (13, 8)], "points": 55},
    "params": {"turnLimit": 14},
  },
  "AMARANTH_MISSION_18": {
    "file": W,
    "note": "Breakout at Draven's Cut. Both mouths at once: six House Amaranth regulars from the west, the Bloom from the east, Undertow under the rubble beside the pads at 3, a second pack and two more regulars at 4, Sirenmaw down the cut at 6. Split smart or don't split at all.",
    "waves": [
      {"a": "hostile_mech_amaranth_01", "n": 2, "t": 1, "at": [(2, 5), (2, 8)], "tier": "D"},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 1, "at": [(2, 6), (2, 7)], "tier": "D"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 1, "at": [(2, 6)], "tier": "D"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 1, "at": [(2, 7)], "tier": "D"},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(29, 5), (29, 8)]},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": [(29, 6), (29, 7)]},
      {"a": "bloom_sporethrower", "n": 3, "t": 1, "at": [(29, 6)]},
      {"a": "bloom_undertow", "n": 5, "t": 3, "at": [(14, 5), (17, 5), (14, 8), (17, 8), (15, 9)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": [(29, 6), (29, 7)]},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 4, "at": [(2, 6)], "tier": "D"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 4, "at": [(2, 7)], "tier": "D"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 4, "at": [(2, 5)], "tier": "D"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 4, "at": [(2, 8)], "tier": "D"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 6, "at": [(29, 4), (29, 9)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_19": {
    "file": W,
    "note": "The Silent Ward. One room at a time, and every room is already occupied: the crawlmass mass in the centre chamber, sporethrowers in three corner rooms, ten Undertow under the rubble seams between them — three in the walls of the squad's own room — packs waking in the rooms behind the squad at 3 and 5, the Choir at 7 and Sirenmaw out of the centre at 9. Nothing called in from inside because nothing got out.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(12, 7)]},
      {"a": "bloom_sporethrower", "n": 6, "t": 1, "at": [(20, 4), (4, 11), (20, 11)]},
      {"a": "bloom_undertow", "n": 10, "t": 1, "at": [(9, 4), (16, 4), (9, 11), (16, 11), (12, 8), (18, 7), (6, 7), (6, 4), (4, 6), (7, 6)], "burrowed": True},
      {"a": "bloom_sporethrower", "n": 3, "t": 2, "at": [(8, 7)]},
      {"a": "bloom_splitfang", "n": 5, "t": 3, "at": [(20, 4)]},
      {"a": "bloom_splitfang", "n": 5, "t": 5, "at": [(4, 11)]},
      {"a": "bloom_choir", "n": 5, "t": 7, "at": [(20, 11)]},
      {"a": "bloom_sirenmaw", "n": 3, "t": 9, "at": [(12, 7)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_20": {
    "file": W,
    "note": "Marrow's Line. She outnumbers you now — seventeen C-tier Line Troopers with three Munti of their own healing behind Marrow's position — and her reserves come through both ridge gaps at 3 and 5. Not a checkpoint dispute.",
    "waves": [
      {"a": "hostile_mech_marrow", "n": 1, "t": 1, "at": [(23, 7)]},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 1, "at": [(22, 4)], "mirror": True, "mirrorScale": 1.5, "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 1, "at": [(22, 10)], "mirror": True, "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 1, "at": [(24, 4)], "mirror": True, "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 1, "at": [(24, 10)], "mirror": True, "tier": "C"},
      {"a": "hostile_mech_amaranth_05", "n": 3, "t": 1, "at": [(24, 6), (24, 8), (24, 7)], "tier": "C"},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 3, "at": [(12, 1)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 3, "at": [(12, 1)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 3, "at": [(13, 1)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 3, "at": [(13, 1)], "tier": "C"},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 5, "at": [(12, 12)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 5, "at": [(12, 12)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 5, "at": [(13, 12)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 5, "at": [(13, 12)], "tier": "C"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_21": {
    "file": W,
    "note": "Cut the Root. The root has grown its own defences: three Gallcyst in the chamber around the Wellroot, Undertow every two turns from 3 (its own rule), a pack already in the chamber's approaches, and Sirenmaw coming in behind the squad at 4 from the deploy side. Eight mechs, one door into the chamber.",
    "waves": [
      {"a": "bloom_wellroot", "n": 1, "t": 1, "at": [(22, 7)]},
      {"a": "bloom_gallcyst", "n": 3, "t": 1, "at": [(20, 5), (20, 9), (22, 4)]},
      {"a": "bloom_splitfang", "n": 6, "t": 1, "at": [(23, 3), (24, 11)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 4, "at": [(2, 1), (2, 13)]},
    ],
    "events": [
      {"id": "ev_cut_the_root_undertow", "turn": 3, "repeat": 2, "spawn": ["bloom_undertow", "bloom_undertow", "bloom_undertow"], "at": [(22, 3), (20, 5), (24, 9)], "burrowed": True},
    ],
    "bonus": None,
  },
  "AMARANTH_MISSION_22": {
    "file": W,
    "note": "Ash on the Water. Two causeways, one dock, Undertow under both causeways, and the water isn't a wall to anything with wings: waves alternate causeways every three turns while single Sirenmaw and then Choir come straight across the sump at the hull, each one a dock-side problem the causeway line can't answer. Hull 300 -> 360 so one flyer landing isn't the mission. Twenty turns. (Sim bot: 0% — it fights forward on the causeways and never garrisons the dock; rated by trace: 2-3 mechs held back at the dock kill each flyer the turn it lands.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(2, 3), (2, 10)]},
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": [(2, 4), (2, 9)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": [(2, 3), (2, 10)]},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(9, 3), (9, 10), (16, 4), (16, 9)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 1, "t": 3, "at": [(12, 6)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 4, "at": [(2, 3), (2, 10)]},
      {"a": "bloom_splitfang", "n": 5, "t": 4, "at": [(2, 4), (2, 9)]},
      {"a": "bloom_sirenmaw", "n": 1, "t": 6, "at": [(12, 7)]},
      {"a": "bloom_splitfang", "n": 8, "t": 7, "at": [(2, 4), (2, 9)]},
      {"a": "bloom_choir", "n": 1, "t": 9, "at": [(12, 6)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 10, "at": [(2, 3), (2, 10)]},
      {"a": "bloom_splitfang", "n": 6, "t": 10, "at": [(2, 4), (2, 9)]},
      {"a": "bloom_undertow", "n": 3, "t": 11, "at": [(20, 3), (20, 10), (18, 6)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 2, "t": 13, "at": [(12, 6), (12, 7)]},
      {"a": "bloom_splitfang", "n": 8, "t": 14, "at": [(2, 4), (2, 9)]},
      {"a": "bloom_choir", "n": 1, "t": 16, "at": [(12, 7)]},
    ],
    "events": [],
    "bonus": None,
    "params": {"assetMaxHp": 360},
  },
  "AMARANTH_MISSION_23": {
    "file": W,
    "note": "The Amaranth Accord. The extraction is behind House Amaranth's own compound wall now, its two gates at the top and bottom corners grown shut with Gallcyst — the bargain, in the flesh — and House Amaranth realises what's walking out the door on turn 1: a six-mech section with its Munti in front of the wall, four more off both flanks at 3, four at 5, and four at 7. Farsight can't be shot; the nine mechs walking her out can, and the regulars are C-tier now. Turn limit 17 -> 11.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(19, 2), (20, 2), (19, 10), (20, 10)]},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 1, "at": [(17, 4)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 1, "at": [(17, 6)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 1, "at": [(17, 8)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 1, "at": [(18, 5)], "tier": "C"},
      {"a": "hostile_mech_amaranth_05", "n": 2, "t": 1, "at": [(18, 7), (18, 3)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 2, "t": 1, "at": [(19, 2), (19, 10)], "tier": "C"},
      {"a": "hostile_mech_amaranth_01", "n": 2, "t": 3, "at": [(10, 1), (10, 11)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 2, "t": 3, "at": [(10, 1), (10, 11)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 5, "at": [(18, 2), (18, 10)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 2, "t": 5, "at": [(18, 2), (18, 10)], "tier": "C"},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 7, "at": [(2, 1)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 7, "at": [(2, 1), (2, 11)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 7, "at": [(2, 11)], "tier": "C"},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 10},
  },
  "AMARANTH_MISSION_24": {
    "file": W,
    "note": "Two Fires. Bloom from the treeline, regulars from the depot, and both keep coming: drift and packs from the north seams at 1, six regulars with a Munti up from the south at 1, Undertow under the field around the pads at 3, the Choir at 4, four more regulars at 5, Sirenmaw at 6, and the last of both at 8. A deserter is down on the west side — one more thing to decide about.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": [(6, 1), (12, 1), (18, 1), (24, 1)]},
      {"a": "bloom_splitfang", "n": 6, "t": 1, "at": [(6, 1), (12, 1), (18, 1), (24, 1)]},
      {"a": "hostile_mech_amaranth_01", "n": 2, "t": 1, "at": [(6, 16), (24, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_02", "n": 1, "t": 1, "at": [(12, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 1, "t": 1, "at": [(18, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 1, "t": 1, "at": [(12, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 1, "at": [(18, 16)], "tier": "C"},
      {"a": "bloom_undertow", "n": 4, "t": 3, "at": [(11, 7), (18, 7), (11, 11), (18, 11)], "burrowed": True},
      {"a": "bloom_choir", "n": 3, "t": 4, "at": [(12, 1), (18, 1)]},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 5, "at": [(6, 16), (24, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_04", "n": 2, "t": 5, "at": [(12, 16), (18, 16)], "tier": "C"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 6, "at": [(6, 1), (24, 1)]},
      {"a": "bloom_splitfang", "n": 6, "t": 8, "at": [(6, 1), (12, 1), (18, 1), (24, 1)]},
      {"a": "hostile_mech_amaranth_01", "n": 1, "t": 8, "at": [(12, 16)], "tier": "C"},
      {"a": "hostile_mech_amaranth_03", "n": 2, "t": 8, "at": [(6, 16), (24, 16)], "tier": "C"},
    ],
    "events": [],
    "bonus": {"kind": "rescue_pilot", "at": (4, 12), "name": "Amaranth Deserter, Wounded", "points": 55},
  },

  # ------------------------------------------------------------------ ACT III
  "AMARANTH_MISSION_25": {
    "file": W,
    "note": "The Reckoning. A coastline, not a wave: the first line from the east at 1, Undertow surfacing mid-field at 2, the Choir over both ridge lines at 3, the second line at 4, Sirenmaw at 5, a third at 7, and the last packs at 9. Twelve mechs, Providence at your back. Everything Command has.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 14, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 6, "t": 2, "at": [(12, 4), (12, 11), (17, 7), (17, 8), (22, 4), (22, 11)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 3, "at": [(12, 2), (22, 2), (12, 13), (22, 13)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 4, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(12, 2), (22, 13)]},
      {"a": "bloom_sporethrower", "n": 6, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 5, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_26": {
    "file": W,
    "note": "The Unnamed Beneath. The hive corridor is grown shut before the extraction — a row of Gallcyst across it at x=20 — with Undertow in every mat on both sides, crawlmass climbing out of the mats as the squad passes, and the Choir following the squad in from the entrance at 6. Ledger can't be shot; the eight mechs cutting her a way out can. Turn limit 20 -> 15. (Sim bot: 0% — its squad stays in the mats fighting Undertow while the extraction target cuts the cork alone at one Gallcyst per four turns; rated by trace: 27-tile corridor at move 5 = 5-6 turns, cork cut in one squad turn, 10-12 with the fights.) A mat patch by the entrance is the bonus, for a Munti who'd rather not go deeper.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 3, "t": 1, "at": [(20, 6), (20, 7), (20, 8)]},
      {"a": "bloom_undertow", "n": 8, "t": 1, "at": [(8, 3), (18, 3), (8, 11), (18, 11), (10, 5), (16, 9), (23, 4), (23, 10)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(9, 4), (9, 10)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 3, "at": [(19, 4), (19, 10)]},
      {"a": "bloom_splitfang", "n": 5, "t": 5, "at": [(24, 5), (24, 9)]},
      {"a": "bloom_choir", "n": 3, "t": 6, "at": [(2, 6), (2, 8)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 8, "at": [(9, 4), (9, 10)]},
    ],
    "events": [],
    "bonus": {"kind": "clear_bloom_patch", "tiles": [(6, 2), (7, 2), (6, 3), (7, 3), (6, 4), (7, 4)], "points": 60},
    "params": {"turnLimit": 15},
  },
  "AMARANTH_MISSION_27": {
    "file": W,
    "note": "Falling Back to Meridian. The surge is already under the line — four Undertow in the zone itself — and it keeps coming: drift and packs from the east at 1, the Choir over the north edge at 3, sporethrowers and packs at 5, Sirenmaw with the second surge at 7, the Choir again at 9, and the last of it at 11. Hold from 10 to 16 on ground the enemy is already standing on. (First cut was 116 hostiles for a hold that has to end clean by 16: 0/50 with eighty-two of them still standing. Fifty-eight was 31/50 at almost nobody down. Seventy now.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 16, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(7, 4), (8, 5), (8, 7), (7, 9)], "burrowed": True},
      {"a": "bloom_choir", "n": 3, "t": 3, "at": [(24, 1), (24, 12)]},
      {"a": "bloom_sporethrower", "n": 6, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 5, "at": "E"},
      {"a": "bloom_crawlmass", "n": 10, "t": 7, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 7, "at": [(12, 1), (12, 12)]},
      {"a": "bloom_splitfang", "n": 10, "t": 9, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 9, "at": [(12, 1), (24, 12)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_28": {
    "file": W,
    "note": "Marrow's Reckoning. Same ridge, same rival, and this time she brought House Amaranth's whole line: a sixteen-mech section with three medics around her at 1, six more over the north edge at 3, seven up from the south at 5, and the last seven from the east at 8 — A-tier regulars, the House's best, and Marrow herself two rungs up. Forty mechs. She's not disengaging.",
    "waves": [
      {"a": "hostile_mech_marrow", "n": 1, "t": 1, "at": [(24, 7)], "tier": "A"},
      {"a": "hostile_mech_amaranth_01", "n": 4, "t": 1, "at": [(24, 4), (24, 10)], "tier": "A"},
      {"a": "hostile_mech_amaranth_02", "n": 4, "t": 1, "at": [(24, 5), (24, 9)], "tier": "A"},
      {"a": "hostile_mech_amaranth_03", "n": 4, "t": 1, "at": [(24, 6), (24, 8)], "tier": "A"},
      {"a": "hostile_mech_amaranth_04", "n": 4, "t": 1, "at": [(26, 5), (26, 9)], "tier": "A"},
      {"a": "hostile_mech_amaranth_05", "n": 2, "t": 1, "at": [(26, 6), (26, 8)], "tier": "A"},
      {"a": "hostile_mech_amaranth_02", "n": 3, "t": 3, "at": [(10, 1), (20, 1)], "tier": "A"},
      {"a": "hostile_mech_amaranth_04", "n": 3, "t": 3, "at": [(10, 1), (20, 1)], "tier": "A"},
      {"a": "hostile_mech_amaranth_01", "n": 3, "t": 5, "at": [(10, 13), (20, 13)], "tier": "A"},
      {"a": "hostile_mech_amaranth_03", "n": 3, "t": 5, "at": [(10, 13), (20, 13)], "tier": "A"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 5, "at": [(20, 13)], "tier": "A"},
      {"a": "hostile_mech_amaranth_02", "n": 2, "t": 8, "at": [(26, 4), (26, 10)], "tier": "A"},
      {"a": "hostile_mech_amaranth_04", "n": 2, "t": 8, "at": [(26, 4), (26, 10)], "tier": "A"},
      {"a": "hostile_mech_amaranth_01", "n": 2, "t": 8, "at": [(26, 7)], "tier": "A"},
      {"a": "hostile_mech_amaranth_05", "n": 1, "t": 8, "at": [(26, 7)], "tier": "A"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_29": {
    "file": W,
    "note": "The Outer Ring Falls. Three directions and the blockhouse's east face is gone — and four Undertow already under its floor, with two more burrowing up into it at 8. The ring is close: everything spawns inside ten tiles of the box, and the first wave is the biggest. Drift, packs and the Choir at 1, sporethrowers and packs at 3, Sirenmaw with the second drift at 5, packs and the Choir at 7, drift at 8, packs at 9, and then nothing: whatever is in the box at 10 has to be cleared out of it by 16. (One door was a fortress, 30/30 at under one mech down against a hundred hostiles. The open face plus the same hundred was 0/30 the other way — the squad kills about three a turn once it is inside the box, so a hold that has to END clean caps the body count around fifty.)",
    "waves": [
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(10, 5), (11, 6), (12, 7), (13, 8)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(16, 2), (16, 13), (9, 1), (13, 14)]},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": [(9, 1), (13, 1), (9, 14), (13, 14)]},
      {"a": "bloom_choir", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 3, "at": [(16, 2), (16, 13)]},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": [(9, 1), (13, 1), (9, 14), (13, 14)]},
      {"a": "bloom_sirenmaw", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": [(16, 2), (16, 13)]},
      {"a": "bloom_splitfang", "n": 4, "t": 7, "at": [(9, 1), (13, 1), (9, 14), (13, 14)]},
      {"a": "bloom_choir", "n": 2, "t": 7, "at": "E"},
      {"a": "bloom_crawlmass", "n": 4, "t": 8, "at": [(16, 2), (16, 13), (9, 1), (13, 14)]},
      {"a": "bloom_undertow", "n": 2, "t": 8, "at": [(11, 6), (12, 8)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 9, "at": [(9, 1), (13, 1), (9, 14), (13, 14)]},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_30": {
    "file": W,
    "note": "Ashes of the Second Ring. City, not open ground: four Gallcyst rooted at the road junctions, six Undertow under the blocks, the drift and packs and sporethrowers already in the streets at 1, the Choir down both roads at 3, packs and Sirenmaw at 5, a second drift at 7, and the Choir with sporethrowers at 9. One street at a time, and every street is already someone's.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(12, 4), (12, 10), (19, 5), (20, 9)]},
      {"a": "bloom_undertow", "n": 6, "t": 1, "at": [(14, 2), (14, 12), (17, 5), (17, 9), (22, 5), (22, 9)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 6, "t": 1, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 3, "at": [(27, 4), (27, 10)]},
      {"a": "bloom_splitfang", "n": 8, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(27, 4), (27, 10)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 9, "at": "E"},
      {"a": "bloom_sporethrower", "n": 6, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_31": {
    "file": W,
    "note": "The Last Convoy. Five people, one road, and the Bloom already has both ends of it: drift on the road flanks ahead at 1, a pack behind the convoy at 2, Undertow under the road at 3, Sirenmaw over the exit side at 4, packs at 5, the big push from both ends at 7, the Choir behind at 8, and Sirenmaw again at 10. The civilians can be shot — three of five have to make it. Turn limit 20 -> 14.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(14, 1), (15, 1), (14, 11), (15, 11)]},
      {"a": "bloom_splitfang", "n": 2, "t": 2, "at": [(24, 1), (24, 11)]},
      {"a": "bloom_undertow", "n": 4, "t": 3, "at": [(10, 6), (6, 5), (18, 7), (8, 6)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 3, "t": 4, "at": [(3, 1), (3, 11)]},
      {"a": "bloom_splitfang", "n": 5, "t": 5, "at": [(14, 1), (14, 11)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 7, "at": [(14, 1), (14, 11), (24, 1), (24, 11)]},
      {"a": "bloom_splitfang", "n": 6, "t": 7, "at": [(14, 1), (14, 11), (24, 1), (24, 11)]},
      {"a": "bloom_choir", "n": 3, "t": 8, "at": [(24, 1), (24, 11)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 10, "at": [(3, 1), (3, 11)]},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 14},
  },
  "AMARANTH_MISSION_32": {
    "file": W,
    "note": "Hold at the Spire. Everything the Bloom has left comes down off the ridge for twenty-two turns: drift and packs at 1, Undertow under the approach at 3, the Choir at 4, sporethrowers and packs at 6, Sirenmaw at 8, the second surge at 10, the Choir at 13, packs and sporethrowers at 15, and Sirenmaw with the last drift at 18. Keep them off the deck.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 14, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 6, "t": 3, "at": [(6, 6), (12, 5), (18, 6), (9, 8), (15, 8), (21, 8)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 4, "at": "E"},
      {"a": "bloom_sporethrower", "n": 8, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 6, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 8, "at": [(2, 1), (23, 1)]},
      {"a": "bloom_crawlmass", "n": 12, "t": 10, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 10, "at": "E"},
      {"a": "bloom_choir", "n": 5, "t": 13, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 15, "at": "E"},
      {"a": "bloom_sporethrower", "n": 6, "t": 15, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 6, "t": 18, "at": [(2, 1), (23, 1)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 18, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_33": {
    "file": W,
    "note": "The Innermost Ring. Five waves, one door, and the ring is already under the floor: eight Undertow in the room at 2, four more burrowing up into it with the fourth wave at 9 and four with the fifth at 15. Drift and packs at 1, the Choir at 4, sporethrowers and packs at 5, Sirenmaw at 7, the second wave at 9, the Choir and sporethrowers at 11, packs and Sirenmaw at 13, and everything at 15 — the wave that has to be in the room with you at 16. Hold from 16 to 22. A hundred and sixty of them. (First cut was 154 hostiles: 6/50; ninety-two was 50/50 at one down. One hundred and twelve was 50/50 too. One hundred and thirty-five was 42/50. One hundred and forty-five now — the cliff is somewhere in the last twenty.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 20, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 14, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 8, "t": 2, "at": [(15, 6), (17, 6), (19, 7), (15, 9), (17, 9), (18, 8)], "burrowed": True},
      {"a": "bloom_choir", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_sporethrower", "n": 10, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 8, "t": 7, "at": [(10, 1), (10, 14)]},
      {"a": "bloom_crawlmass", "n": 14, "t": 9, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 9, "at": "E"},
      {"a": "bloom_undertow", "n": 2, "t": 9, "at": [(15, 6), (19, 7)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 11, "at": "E"},
      {"a": "bloom_sporethrower", "n": 6, "t": 11, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 13, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 13, "at": [(10, 1), (10, 14)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 15, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 15, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 15, "at": [(10, 1), (10, 14)]},
      {"a": "bloom_undertow", "n": 2, "t": 15, "at": [(17, 9), (18, 8)], "burrowed": True},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_34": {
    "file": W,
    "note": "No Word from the Fleet. Every direction at once, for fourteen turns: drift and packs from all eight seams at 1, ten Undertow under the ground around the pads at 2, the Choir at 3, sporethrowers and packs at 5, Sirenmaw at 7, the second surge with more Undertow at 8, the Choir and sporethrowers at 10, packs and Sirenmaw at 11, and the last of it at 13. Nobody's coming.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 20, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 12, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 10, "t": 2, "at": [(9, 5), (16, 5), (9, 10), (16, 10), (12, 4), (13, 11), (8, 7), (17, 8), (12, 11), (13, 4)], "burrowed": True},
      {"a": "bloom_choir", "n": 6, "t": 3, "at": "E"},
      {"a": "bloom_sporethrower", "n": 10, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 8, "t": 7, "at": "E"},
      {"a": "bloom_crawlmass", "n": 16, "t": 8, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 8, "at": "E"},
      {"a": "bloom_undertow", "n": 6, "t": 8, "at": [(9, 5), (16, 5), (9, 10), (16, 10), (12, 4), (13, 11)], "burrowed": True},
      {"a": "bloom_choir", "n": 6, "t": 10, "at": "E"},
      {"a": "bloom_sporethrower", "n": 8, "t": 10, "at": "E"},
      {"a": "bloom_splitfang", "n": 12, "t": 11, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 6, "t": 11, "at": "E"},
      {"a": "bloom_crawlmass", "n": 14, "t": 13, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 13, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "AMARANTH_MISSION_35": {
    "file": W,
    "note": "The Last Ring. The Unnamed breaches at 6 — INSIDE the ring, in the room the company is holding, exactly where Rourke said it wouldn't be allowed to — and everything else is timed around it: drift and packs at 1, Undertow in the room at 2, the Choir at 4, sporethrowers with the breach at 6, Sirenmaw and packs at 8, the second surge at 10, the Choir and sporethrowers at 12, the last packs at 14. Nobody's asking you to kill it; the zone won't read clear until you do. Hold from 16 to 22. (First cut was 101 plus The Unnamed: 0/50. Sixty-seven plus The Unnamed was 32/50; seventy-nine plus The Unnamed was 44/50; ninety plus The Unnamed now; the hold has to end clean by 22.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 16, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 12, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 6, "t": 2, "at": [(16, 7), (18, 7), (16, 10), (18, 10)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 4, "at": "E"},
      {"a": "bloom_sporethrower", "n": 5, "t": 6, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 8, "at": [(11, 2), (11, 15)]},
      {"a": "bloom_splitfang", "n": 7, "t": 8, "at": "E"},
      {"a": "bloom_crawlmass", "n": 12, "t": 10, "at": "E"},
      {"a": "bloom_splitfang", "n": 5, "t": 10, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 12, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 12, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 14, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 14, "at": [(16, 7), (18, 7), (16, 10), (18, 10)], "burrowed": True},
    ],
    "events": [
      {"id": "ev_last_ring_unnamed_breach", "turn": 6, "spawn": ["bloom_unnamed"], "at": [(18, 8)]},
    ],
    "bonus": None,
  },
  "AMARANTH_MISSION_36": {
    "file": W,
    "note": "Until Relief. The whole sector, for sixteen turns: drift and packs from every seam at 1, eight Undertow under the ground around the pads at 2, the Choir at 3, sporethrowers and packs at 4, Sirenmaw at 6, the second surge with the Choir at 7, sporethrowers at 9, packs and Sirenmaw at 10, the third surge at 12, Gallcyst rooting in beside the pads at 13, and the Choir with the last packs at 14. The fleet lands at 16.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 16, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 8, "t": 2, "at": [(9, 6), (20, 6), (9, 10), (20, 10), (14, 5), (15, 12), (10, 8), (19, 8)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_sporethrower", "n": 10, "t": 4, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 6, "t": 6, "at": "E"},
      {"a": "bloom_crawlmass", "n": 14, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 7, "at": "E"},
      {"a": "bloom_sporethrower", "n": 8, "t": 9, "at": "E"},
      {"a": "bloom_splitfang", "n": 12, "t": 10, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 5, "t": 10, "at": "E"},
      {"a": "bloom_crawlmass", "n": 14, "t": 12, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 12, "at": "E"},
      {"a": "bloom_gallcyst", "n": 4, "t": 13, "at": [(10, 7), (19, 7), (10, 10), (19, 10)]},
      {"a": "bloom_choir", "n": 6, "t": 14, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 14, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },

  # ================================================================== HOUSE AMARANTH
  "HOUSE_AMARANTH_MISSION_1": {
    "file": H,
    "note": "First Harvest. A quiet morning until the second drift comes in off the east edge at 2 — the way they always do, except from the side nobody was watching — with a third at 4 and a splitfang pack at 5. Crawlmass only. The mat on the north terrace is the bonus: burn it while the drift is still coming.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 3, "t": 2, "at": [(13, 3), (13, 5)]},
      {"a": "bloom_crawlmass", "n": 4, "t": 4, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 6, "at": [(13, 1)]},
    ],
    "events": [],
    "bonus": {"kind": "clear_bloom_patch", "tiles": [(2, 2), (3, 2), (4, 2), (2, 3), (3, 3), (4, 3)], "points": 30},
  },
  "HOUSE_AMARANTH_MISSION_2": {
    "file": H,
    "note": "The Long Contract. Exactly one door, as promised, and the Bloom is already between the pads and it: a pair in the grain store at 1, sporethrowers behind the pads at 2, a second pack on the doorway's flanks at 3, a pack behind the squad at 4, the seams and more sporethrowers at 5, packs at 7 and 9. (A first cut widened the door and ran the hold zone out through it; reverted to keep the briefing's promise.)",
    "waves": [
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": [(4, 3), (4, 7)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 2, "at": [(2, 1), (2, 9)]},
      {"a": "bloom_splitfang", "n": 3, "t": 3, "at": [(5, 2), (5, 8)]},
      {"a": "bloom_splitfang", "n": 2, "t": 4, "at": [(1, 2), (1, 8)]},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 5, "at": [(4, 3), (4, 7)]},
      {"a": "bloom_splitfang", "n": 3, "t": 7, "at": [(4, 2), (4, 8)]},
      {"a": "bloom_splitfang", "n": 3, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_3": {
    "file": H,
    "note": "Second Harvest. The field closing behind Orin is a real gap now: a sump line at x=17 with a two-tile break, the seams behind it, two Gallcyst grown into the break and an Undertow behind them. The squad has to cut it open under acid while a second drift arrives behind them at 3, sporethrowers take both edges at 4, and a pack comes through from the seams at 5. Turn limit 14 -> 10.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 1, "t": 1, "at": [(17, 6)]},
      {"a": "bloom_undertow", "n": 1, "t": 1, "at": [(17, 5)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 3, "at": [(1, 2), (1, 10)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 4, "at": [(10, 1), (10, 11)]},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 10},
  },
  "HOUSE_AMARANTH_MISSION_4": {
    "file": H,
    "note": "Good Neighbors. Same drift, same terrace — and this time a pack comes across the checkpoint road at 2 from the side Warden Company is standing on, sporethrowers set up on the road at 4 with a second drift, and a last pack at 6. Whatever they report back, let it be that it was handled.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 7, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 2, "at": [(16, 2), (16, 7)]},
      {"a": "bloom_crawlmass", "n": 5, "t": 4, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 4, "at": [(16, 4), (16, 5)]},
      {"a": "bloom_splitfang", "n": 2, "t": 6, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_5": {
    "file": H,
    "note": "The Seal Arrives. Hold the dais through the review — with three Undertow under the dais itself, packs and sporethrowers from the south seams at 1, drift in off both edges at 2, and packs at 3, 5 and 7. Nothing about today can look like the program straining.",
    "waves": [
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 3, "t": 1, "at": [(9, 4), (10, 5), (8, 6)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 4, "t": 2, "at": [(1, 5), (18, 5)]},
      {"a": "bloom_splitfang", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_6": {
    "file": H,
    "note": "House Colors. What's coming up through the drainage past the gate is more than a drift: packs with it at 1, sporethrowers on the far side of the wall, packs down both flanking roads at 3, Undertow surfacing at the gate itself at 5 with a second drift, and a last pack at 7. Clear the gate first.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 7, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": [(15, 4), (15, 7)]},
      {"a": "bloom_splitfang", "n": 3, "t": 3, "at": [(18, 1), (18, 10)]},
      {"a": "bloom_undertow", "n": 2, "t": 5, "at": [(10, 4), (10, 7)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_7": {
    "file": H,
    "note": "Deeper Terraces. The upper tier's irrigation channel (sump, impassable) has two crossings and both have grown shut — a Gallcyst pair in each — with sporethrowers on the tier above shooting down and Undertow under the flat. Drift on the flat at 1, packs at the top-left seam at 4 waiting for whoever comes through, more drift at 6. Get up the ridge, get her out. Turn limit 12 -> 10.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(5, 3), (5, 4), (14, 3), (14, 4)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": [(4, 5), (14, 7)]},
      {"a": "bloom_splitfang", "n": 2, "t": 1, "at": [(14, 7)]},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": [(9, 1), (16, 1)]},
      {"a": "bloom_undertow", "n": 2, "t": 2, "at": [(6, 7), (12, 7)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 4, "at": [(3, 1), (16, 1)]},
      {"a": "bloom_crawlmass", "n": 5, "t": 6, "at": [(4, 5), (14, 7)]},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 10},
  },
  "HOUSE_AMARANTH_MISSION_8": {
    "file": H,
    "note": "The Quiet Growth. Four drifts, all sides, all at once — and three Undertow under the post itself at 2. Sporethrowers at 3, a pack at 4, more of both at 6 and 8. Ten turns of not staying where it's put.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 3, "t": 2, "at": [(5, 4), (9, 7), (7, 8)], "burrowed": True},
      {"a": "bloom_sporethrower", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_crawlmass", "n": 4, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 8, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 8, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_9": {
    "file": H,
    "note": "Loyalist Eyes. Two gates, one auditor, nothing difficult — except the packs through both gates at 1, 3, 5, 7 and 9, sporethrowers at 2 and 7, and two Undertow under the zone itself at 4. Give her nothing to write home about.",
    "waves": [
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 2, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_undertow", "n": 2, "t": 4, "at": [(8, 6), (7, 7)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 7, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_10": {
    "file": H,
    "note": "The Choir, Heard From Afar. The handful that didn't take the redirect is eight of them, in three voices: four with a crawlmass screen from the east seams, two over the north mat at 3, two over the south mat at 5, and a pack up the middle at 6 for whoever scattered.",
    "waves": [
      {"a": "bloom_choir", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 5, "t": 1, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 3, "at": [(6, 1), (14, 1)]},
      {"a": "bloom_choir", "n": 2, "t": 5, "at": [(6, 11), (14, 11)]},
      {"a": "bloom_splitfang", "n": 3, "t": 6, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_11": {
    "file": H,
    "note": "What the Terraces Cost. The crop's grown in thick enough to lose a mech in — a sump line at x=16 now, with the only way to the tree line through the three-tile break at rows 5-7, and three Gallcyst grown into it. Drift and packs at 1, Undertow under the crop at 2, sporethrowers at 3, a pack at 4, and the Choir that passed last night at 6. Turn limit 15 -> 10.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(16, 5), (16, 6), (16, 7), (17, 6)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(9, 5), (9, 7), (12, 6), (17, 6)], "burrowed": True},
      {"a": "bloom_sporethrower", "n": 2, "t": 3, "at": [(6, 1), (14, 1)]},
      {"a": "bloom_splitfang", "n": 4, "t": 4, "at": [(6, 9)]},
      {"a": "bloom_choir", "n": 3, "t": 6, "at": [(14, 1)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 9},
  },
  "HOUSE_AMARANTH_MISSION_12": {
    "file": H,
    "note": "Harvest's End. Whatever's coming through the relay comes through it: drift and packs from the seams at 1 with three Undertow under the relay zone itself, sporethrowers at 3, packs at 4, Sirenmaw over both corners at 5, the drift that has to be in the zone with you at 7 spawned at 6, the Choir at 8, and the last pack at 10. Hold from 7 to 12. However long it actually takes.",
    "waves": [
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 3, "t": 1, "at": [(8, 6), (10, 7), (9, 8)], "burrowed": True},
      {"a": "bloom_sporethrower", "n": 3, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 4, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 5, "at": [(2, 1), (17, 1)]},
      {"a": "bloom_crawlmass", "n": 5, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 6, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 8, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 10, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },

  "HOUSE_AMARANTH_MISSION_13": {
    "file": H,
    "note": "New Terraces, New Faces. The terrace's own point-defence — four Gallcyst in the scaffold block — doesn't know the new pilots from a threat, and the Bloom is already here: drift, packs and sporethrowers at 1, Undertow under the flat at 3, a second drift at 5, the Choir at 7.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(8, 3), (11, 3), (8, 4), (11, 4)]},
      {"a": "bloom_sporethrower", "n": 4, "t": 1, "at": [(6, 4), (13, 4), (6, 5), (13, 5)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 3, "at": [(5, 7), (14, 7), (9, 7), (10, 7)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 3, "t": 5, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 7, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_14": {
    "file": H,
    "note": "The Governor's Patience. Quiet where you can, fast where you can't: three Gallcyst grown across the checkpoint itself, four Undertow under the rubble along the road, drift and packs from the seams at 1, sporethrowers on the north edge at 3, a second drift at 5, and the Choir behind at 6. Turn limit 14 -> 7.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 4, "t": 1, "at": [(19, 4), (19, 5), (19, 6), (20, 5)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(4, 3), (17, 4), (4, 7), (17, 7)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 9, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 3, "t": 3, "at": [(10, 1), (12, 1)]},
      {"a": "bloom_crawlmass", "n": 5, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 6, "at": [(2, 1)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 8},
  },
  "HOUSE_AMARANTH_MISSION_15": {
    "file": H,
    "note": "Rootbound. Rooted in on all four corners — sporethrowers in each — with four Undertow under the zone itself, drift and packs at 1, packs at 3, Sirenmaw off the corners at 4, a second drift at 5, the Choir at 7, and a last pack at 9. Hold from 6 to 10. There isn't a safe direction left.",
    "waves": [
      {"a": "bloom_sporethrower", "n": 4, "t": 1, "at": [(1, 2), (18, 2), (1, 9), (18, 9)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(7, 5), (12, 5), (7, 6), (12, 6)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 4, "at": [(1, 2), (18, 9)]},
      {"a": "bloom_crawlmass", "n": 6, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_16": {
    "file": H,
    "note": "The Long Ledger. No House colours, better gear: eight unmarked D-tier mechs down the depot road at 1, four over the north gaps at 3, six more from the seams at 5, and six C-tier at 7 — whoever sent them sent their best last.",
    "waves": [
      {"a": "hostile_mech_01", "n": 2, "t": 1, "at": "E", "tier": "D"},
      {"a": "hostile_mech_02", "n": 2, "t": 1, "at": "E", "tier": "D"},
      {"a": "hostile_mech_03", "n": 2, "t": 1, "at": "E", "tier": "D"},
      {"a": "hostile_mech_04", "n": 2, "t": 1, "at": "E", "tier": "D"},
      {"a": "hostile_mech_02", "n": 2, "t": 3, "at": [(5, 1), (16, 1)], "tier": "D"},
      {"a": "hostile_mech_04", "n": 2, "t": 3, "at": [(5, 1), (16, 1)], "tier": "D"},
      {"a": "hostile_mech_01", "n": 2, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_03", "n": 2, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_02", "n": 2, "t": 5, "at": "E", "tier": "D"},
      {"a": "hostile_mech_01", "n": 2, "t": 7, "at": "E", "tier": "C"},
      {"a": "hostile_mech_02", "n": 1, "t": 7, "at": "E", "tier": "C"},
      {"a": "hostile_mech_03", "n": 2, "t": 7, "at": "E", "tier": "C"},
      {"a": "hostile_mech_04", "n": 1, "t": 7, "at": "E", "tier": "C"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_17": {
    "file": H,
    "note": "What Grows Beneath. The terrace lane between two irrigation channels, and the lane's east end grown shut — four Gallcyst across x=20 — with Undertow under the lane at 2, packs from the channel crossings at 1, 2 and 4, the drift up the middle, Sirenmaw over the north crossing at 5 and the Choir over the south at 6. Turn limit 12 -> 10.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 6, "t": 1, "at": [(20, 3), (20, 4), (20, 5), (20, 6), (21, 4), (21, 5)]},
      {"a": "bloom_splitfang", "n": 6, "t": 1, "at": [(4, 2), (18, 2), (4, 7), (18, 7)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(11, 5)]},
      {"a": "bloom_undertow", "n": 5, "t": 2, "at": [(8, 4), (14, 6), (10, 3), (16, 5), (18, 4)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 2, "at": [(4, 8), (18, 8)]},
      {"a": "bloom_splitfang", "n": 4, "t": 4, "at": [(4, 1), (18, 1)]},
      {"a": "bloom_sirenmaw", "n": 3, "t": 5, "at": [(11, 1)]},
      {"a": "bloom_choir", "n": 3, "t": 6, "at": [(11, 8)]},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 10},
  },
  "HOUSE_AMARANTH_MISSION_18": {
    "file": H,
    "note": "Cultivator's Gambit. Down and hold — under Sirenmaw already circling the patch, drift and packs on the ground, Undertow under the landing itself at 2, a second drift at 4, the Choir at 6, and Sirenmaw again at 8. Nobody told the Bloom this ground's spoken for.",
    "waves": [
      {"a": "bloom_sirenmaw", "n": 6, "t": 1, "at": [(8, 2), (9, 2), (16, 4), (17, 4), (3, 5), (11, 7)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 1, "at": [(8, 2), (16, 4), (3, 5), (11, 7)]},
      {"a": "bloom_splitfang", "n": 3, "t": 1, "at": [(16, 4), (3, 5)]},
      {"a": "bloom_undertow", "n": 3, "t": 2, "at": [(9, 3), (11, 6), (13, 3)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 4, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 6, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 8, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_19": {
    "file": H,
    "note": "The Weight of the Seal. No managed lane: three Gallcyst rooted beside the overlook, packs and sporethrowers at 1, Undertow under the position at 2, packs at 3, Sirenmaw at 5, packs and the Choir at 7, a last pack at 9. Hold from 6 to 10 while Halcyon watches.",
    "waves": [
      {"a": "bloom_gallcyst", "n": 3, "t": 1, "at": [(9, 3), (9, 5), (16, 4)]},
      {"a": "bloom_splitfang", "n": 5, "t": 1, "at": "E"},
      {"a": "bloom_sporethrower", "n": 2, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 2, "t": 2, "at": [(12, 4), (11, 5)], "burrowed": True},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 3, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 4, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_20": {
    "file": H,
    "note": "Marrow's Line. Rourke's push is a real one, and she's standing in the line's own trench gap: the drainage trench at x=18 is sump now with a two-tile break at rows 5-6, Rourke's two elements and two Tanks IN the break, six more C-tier Warden troopers around it at 1, four coming up BEHIND the squad at 2, four more at 3, four at 5. Marrow can't be shot on her way out; the nine mechs covering her withdrawal can, and the Tank at the back gets caught. Turn limit 13 -> 7 — a withdrawal, not a fight; nobody plays hero on her ground today.",
    "waves": [
      {"a": "hostile_mech_rourke", "n": 2, "t": 1, "at": [(17, 5), (17, 6)]},
      {"a": "hostile_mech_warden_01", "n": 2, "t": 1, "at": [(18, 5), (18, 6)], "tier": "C"},
      {"a": "hostile_mech_warden_02", "n": 2, "t": 1, "at": [(10, 2), (10, 9)], "tier": "C"},
      {"a": "hostile_mech_warden_03", "n": 2, "t": 1, "at": [(13, 3), (13, 8)], "tier": "C"},
      {"a": "hostile_mech_warden_04", "n": 2, "t": 1, "at": [(16, 4), (16, 7)], "tier": "C"},
      {"a": "hostile_mech_warden_02", "n": 2, "t": 2, "at": [(1, 1), (1, 10)], "tier": "C"},
      {"a": "hostile_mech_warden_03", "n": 2, "t": 2, "at": [(1, 1), (1, 10)], "tier": "C"},
      {"a": "hostile_mech_warden_02", "n": 2, "t": 3, "at": [(20, 2), (20, 9)], "tier": "C"},
      {"a": "hostile_mech_warden_04", "n": 2, "t": 3, "at": [(20, 2), (20, 9)], "tier": "C"},
      {"a": "hostile_mech_warden_01", "n": 2, "t": 5, "at": [(6, 1), (6, 10)], "tier": "C"},
      {"a": "hostile_mech_warden_03", "n": 2, "t": 5, "at": [(6, 1), (6, 10)], "tier": "C"},
    ],
    "events": [],
    "bonus": None,
    "params": {"turnLimit": 7},
  },

  "HOUSE_AMARANTH_MISSION_21": {
    "file": H,
    "note": "After the Line. Just the Bloom, same as always — but it's already on the terraces: ten Undertow in the rubble and under the pads' flanks, drift and packs mid-field at 1, sporethrowers over the rubble at 2, the Choir at 3, packs behind the line with Sirenmaw at 5, a second drift at 7, the Choir again at 9. The terraces don't get to slip.",
    "waves": [
      {"a": "bloom_undertow", "n": 10, "t": 1, "at": [(8, 3), (13, 3), (8, 5), (13, 5), (10, 2), (11, 6), (6, 4), (15, 4), (3, 1), (3, 9)], "burrowed": True},
      {"a": "bloom_crawlmass", "n": 16, "t": 1, "at": [(12, 2), (12, 8), (13, 4), (13, 6)]},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": [(12, 2), (12, 8), (13, 4), (13, 6)]},
      {"a": "bloom_sporethrower", "n": 4, "t": 2, "at": [(14, 3), (14, 7)]},
      {"a": "bloom_choir", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 10, "t": 5, "at": [(10, 1), (10, 9)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(2, 0), (17, 10)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 9, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_22": {
    "file": H,
    "note": 'Audit Under Fire. Two causeways, one relay floor, and the water is nothing to anything with wings — and the corners behind the pads were never sealed: drift and packs on both causeways at 1 with sporethrowers already at the causeway mouths, Undertow under the causeways at 2, a Sirenmaw at the relay and a pack in the rear corners at 3, sporethrowers with the second drift at 4, Undertow surfacing INSIDE the relay floor at 5, more Sirenmaw at 6, packs at 7, Sirenmaw and a pack in the corners at 8, a Choir at 9, the big push at 10, Undertow in the floor again at 11, Sirenmaw at 12. Relay 300 -> 360.',
    "waves": [
      {"a": "bloom_crawlmass", "n": 12, "t": 1, "at": [(2, 2), (2, 7)]},
      {"a": "bloom_splitfang", "n": 6, "t": 1, "at": [(7, 2), (7, 7)]},
      {"a": "bloom_sporethrower", "n": 4, "t": 1, "at": [(12, 3), (12, 8)]},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(9, 2), (9, 7), (12, 3), (12, 8)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 1, "t": 3, "at": [(6, 5)]},
      {"a": "bloom_splitfang", "n": 4, "t": 3, "at": [(17, 1), (17, 9)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 4, "at": [(2, 2), (2, 7)]},
      {"a": "bloom_sporethrower", "n": 6, "t": 4, "at": [(2, 3), (2, 8)]},
      {"a": "bloom_undertow", "n": 2, "t": 5, "at": [(16, 2), (16, 7)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 2, "t": 6, "at": [(6, 5), (6, 6)]},
      {"a": "bloom_splitfang", "n": 8, "t": 7, "at": [(2, 2), (2, 7)]},
      {"a": "bloom_sirenmaw", "n": 2, "t": 8, "at": [(17, 1), (17, 9)]},
      {"a": "bloom_splitfang", "n": 4, "t": 8, "at": [(17, 1), (17, 9)]},
      {"a": "bloom_choir", "n": 1, "t": 9, "at": [(6, 5)]},
      {"a": "bloom_crawlmass", "n": 10, "t": 10, "at": [(2, 2), (2, 7)]},
      {"a": "bloom_splitfang", "n": 6, "t": 10, "at": [(7, 2), (7, 7)]},
      {"a": "bloom_undertow", "n": 2, "t": 11, "at": [(18, 4), (18, 6)], "burrowed": True},
      {"a": "bloom_sirenmaw", "n": 2, "t": 12, "at": [(6, 5), (6, 6)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'assetMaxHp': 360},
  },
  "HOUSE_AMARANTH_MISSION_23": {
    "file": H,
    "note": "The Root Answers Back. Hold the ring with the Wellroot's reach across its east half — and it answers with everything: a Choir and drift at 1, Undertow in the ring at 2, the Choir and packs at 4, Sirenmaw and drift at 6, the push that has to be in the ring with you at 8 spawned at 7, packs at 9, the Choir at 11. Hold from 8 to 12. Nobody fires on the root unless it moves first. (First cut: eight Choir at 1 was a wall the squad never punched through by turn 8 — 20/20 zone losses with everyone alive.)",
    "waves": [
      {"a": "bloom_wellroot", "n": 1, "t": 1, "at": [(14, 4)]},
      {"a": "bloom_choir", "n": 3, "t": 1, "at": "E"},
      {"a": "bloom_crawlmass", "n": 12, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(9, 3), (12, 5), (10, 4), (11, 3)], "burrowed": True},
      {"a": "bloom_choir", "n": 2, "t": 4, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 4, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 6, "at": [(1, 1), (20, 9)]},
      {"a": "bloom_crawlmass", "n": 8, "t": 6, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 7, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 7, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 9, "at": "E"},
      {"a": "bloom_choir", "n": 2, "t": 11, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_24": {
    "file": H,
    "note": "Seizure Order. The Governor can be shot, and sector command's regulars are B-tier now: ten from the seams at 1, four A-tier between her and the tree line at 3, four behind the squad at 5, and four A-tier at 7 — the liability review's own escort. Turn limit 14 -> 9.",
    "waves": [
      {"a": "hostile_mech_loyalist_01", "n": 3, "t": 1, "at": "E", "tier": "B"},
      {"a": "hostile_mech_loyalist_02", "n": 2, "t": 1, "at": "E", "tier": "B"},
      {"a": "hostile_mech_loyalist_03", "n": 3, "t": 1, "at": "E", "tier": "B"},
      {"a": "hostile_mech_loyalist_04", "n": 2, "t": 1, "at": "E", "tier": "B"},
      {"a": "hostile_mech_loyalist_01", "n": 2, "t": 3, "at": [(20, 1), (20, 9)], "tier": "A"},
      {"a": "hostile_mech_loyalist_03", "n": 2, "t": 3, "at": [(20, 1), (20, 9)], "tier": "A"},
      {"a": "hostile_mech_loyalist_02", "n": 2, "t": 5, "at": [(1, 1), (1, 9)], "tier": "B"},
      {"a": "hostile_mech_loyalist_04", "n": 2, "t": 5, "at": [(1, 1), (1, 9)], "tier": "B"},
      {"a": "hostile_mech_loyalist_01", "n": 1, "t": 7, "at": "E", "tier": "A"},
      {"a": "hostile_mech_loyalist_02", "n": 1, "t": 7, "at": "E", "tier": "A"},
      {"a": "hostile_mech_loyalist_03", "n": 1, "t": 7, "at": "E", "tier": "A"},
      {"a": "hostile_mech_loyalist_04", "n": 1, "t": 7, "at": "E", "tier": "A"},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 9},
  },
  "HOUSE_AMARANTH_MISSION_25": {
    "file": H,
    "note": "Going Dark. Nobody's coming, for fourteen turns: drift and packs at 1, six Undertow under the ground around the post at 2, the Choir at 3, packs and sporethrowers at 5, Sirenmaw at 7, the second surge at 8, the Choir and sporethrowers at 10, packs and Sirenmaw at 11, the last of it at 13. (First cut at half again as much never got past turn 9.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 16, "t": 1, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 1, "at": "E"},
      {"a": "bloom_undertow", "n": 6, "t": 2, "at": [(6, 4), (13, 4), (6, 7), (13, 7), (9, 2), (10, 8)], "burrowed": True},
      {"a": "bloom_choir", "n": 4, "t": 3, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 5, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 7, "at": "E"},
      {"a": "bloom_crawlmass", "n": 12, "t": 8, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 8, "at": "E"},
      {"a": "bloom_choir", "n": 4, "t": 10, "at": "E"},
      {"a": "bloom_sporethrower", "n": 4, "t": 10, "at": "E"},
      {"a": "bloom_splitfang", "n": 8, "t": 11, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 3, "t": 11, "at": "E"},
      {"a": "bloom_crawlmass", "n": 12, "t": 13, "at": "E"},
      {"a": "bloom_splitfang", "n": 6, "t": 13, "at": "E"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_26": {
    "file": H,
    "note": "The Bramble. Not drift, and not coming from the seams — it's already at the pads when the mission opens: twenty of them in a ring three tiles out at 1 with four Choir singing them forward, six Undertow under the pads' own flanks at 2, ten more out of the west mats behind the squad at 3, ten from the seams with Sirenmaw over the pads at 5, and ten mid-field at 7. It doesn't get a containment line. (Thirteen from the far seams walked into a fifteen-mech firing line one at a time, and so did fifty from five tiles out: 20/20 both times. A Bramble does about thirty to an A-tier frame and dies to three hits; against this squad it only counts when it arrives all at once from every side with the Choir behind it.)",
    "waves": [
      {"a": "bloom_bramble", "n": 20, "t": 1, "at": [(3, 1), (3, 9), (4, 3), (4, 7), (5, 5), (2, 0), (2, 10), (4, 5)]},
      {"a": "bloom_choir", "n": 4, "t": 1, "at": [(6, 2), (6, 8)]},
      {"a": "bloom_undertow", "n": 6, "t": 2, "at": [(2, 2), (2, 8), (3, 4), (3, 6), (1, 2), (1, 8)], "burrowed": True},
      {"a": "bloom_bramble", "n": 10, "t": 3, "at": [(4, 1), (4, 9)]},
      {"a": "bloom_bramble", "n": 10, "t": 5, "at": "E"},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(2, 0), (2, 10)]},
      {"a": "bloom_bramble", "n": 10, "t": 7, "at": [(10, 4), (10, 6)]},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_27": {
    "file": H,
    "note": "Salvage the Season. Five technicians, eighteen tiles of terrace, and the Bramble already through the north terrace: packs mid-field at 2 and 4, Undertow at the route's edges at 3, Sirenmaw over the deploy side at 5, a pack landing on the tree line itself at 7, and a last one at 9. Four of five have to make it. Turn limit 16 -> 12. (First cut put Undertow ON the route; they surfaced under the technicians and 20/20 runs lost two by turn 6.)",
    "waves": [
      {"a": "bloom_bramble", "n": 3, "t": 2, "at": [(10, 1), (10, 8)]},
      {"a": "bloom_undertow", "n": 2, "t": 3, "at": [(8, 2), (14, 7)], "burrowed": True},
      {"a": "bloom_bramble", "n": 4, "t": 4, "at": [(10, 1), (10, 8)]},
      {"a": "bloom_sirenmaw", "n": 2, "t": 5, "at": [(1, 1), (1, 8)]},
      {"a": "bloom_bramble", "n": 3, "t": 7, "at": [(20, 1), (20, 8)]},
      {"a": "bloom_bramble", "n": 3, "t": 9, "at": [(10, 1), (10, 8)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 12},
  },
  "HOUSE_AMARANTH_MISSION_28": {
    "file": H,
    "note": "Marrow's Choice. Rourke came back with Warden Company's best, A-tier troopers, and she didn't stop at the tree line — she's three tiles off the pads when the mission opens with six, six more a turn behind her, four behind the squad's own line at 3, four from the seams at 5, four from the east at 7. No lane out this time. (Fourteen tiles of approach into a fifteen-mech firing line: 20/20; five tiles: 20/20 again — a fifteen-mech alpha strike with ambush and missiles kills eight A-tier frames a turn, so the only fight is the one that lands first.)",
    "waves": [
      {"a": "hostile_mech_rourke", "n": 1, "t": 1, "at": [(5, 6)], "tier": "A"},
      {"a": "hostile_mech_warden_01", "n": 2, "t": 1, "at": [(5, 4), (5, 8)], "tier": "A"},
      {"a": "hostile_mech_warden_02", "n": 1, "t": 1, "at": [(4, 2)], "tier": "A"},
      {"a": "hostile_mech_warden_03", "n": 2, "t": 1, "at": [(5, 5), (5, 7)], "tier": "A"},
      {"a": "hostile_mech_warden_04", "n": 1, "t": 1, "at": [(4, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_01", "n": 1, "t": 1, "at": [(9, 4)], "tier": "A"},
      {"a": "hostile_mech_warden_02", "n": 2, "t": 1, "at": [(9, 2), (9, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_03", "n": 1, "t": 1, "at": [(9, 8)], "tier": "A"},
      {"a": "hostile_mech_warden_04", "n": 2, "t": 1, "at": [(10, 5), (10, 7)], "tier": "A"},
      {"a": "hostile_mech_warden_02", "n": 2, "t": 3, "at": [(2, 1), (2, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_04", "n": 2, "t": 3, "at": [(2, 1), (2, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_01", "n": 2, "t": 5, "at": "E", "tier": "A"},
      {"a": "hostile_mech_warden_03", "n": 2, "t": 5, "at": "E", "tier": "A"},
      {"a": "hostile_mech_warden_01", "n": 1, "t": 7, "at": [(25, 1), (25, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_02", "n": 1, "t": 7, "at": [(25, 1)], "tier": "A"},
      {"a": "hostile_mech_warden_03", "n": 1, "t": 7, "at": [(25, 10)], "tier": "A"},
      {"a": "hostile_mech_warden_04", "n": 1, "t": 7, "at": [(25, 1)], "tier": "A"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_29": {
    "file": H,
    "note": "The Governor's Answer. The seizure force lands on four sides of the relay, a section a turn, B-tier then A-tier — with Undertow under the zone at 2, five-mech sections from 7 on, and the section that has to be in the zone with you at 12 landing two tiles from the ring at 11 with more Undertow, and one more at 12 from the west. Hold from 12 to 16 and make them pay for it.",
    "waves": [
      {"a": "hostile_mech_loyalist_01", "n": 6, "t": 1, "at": [(9, 1), (10, 1)], "tier": "B"},
      {"a": "bloom_undertow", "n": 3, "t": 2, "at": [(10, 4), (12, 3), (11, 5)], "burrowed": True},
      {"a": "hostile_mech_loyalist_02", "n": 4, "t": 2, "at": [(6, 3), (6, 5)], "tier": "B"},
      {"a": "hostile_mech_loyalist_03", "n": 4, "t": 3, "at": [(22, 3), (23, 3)], "tier": "B"},
      {"a": "hostile_mech_loyalist_04", "n": 4, "t": 4, "at": [(9, 8), (10, 8)], "tier": "A"},
      {"a": "hostile_mech_loyalist_02", "n": 4, "t": 5, "at": [(22, 5), (23, 5)], "tier": "A"},
      {"a": "hostile_mech_loyalist_01", "n": 5, "t": 7, "at": [(9, 1), (10, 1)], "tier": "A"},
      {"a": "hostile_mech_loyalist_03", "n": 5, "t": 9, "at": [(9, 8), (10, 8)], "tier": "A"},
      {"a": "hostile_mech_loyalist_04", "n": 6, "t": 11, "at": [(14, 3), (14, 5), (15, 4)], "tier": "A"},
      {"a": "bloom_undertow", "n": 2, "t": 11, "at": [(9, 4), (12, 4)], "burrowed": True},
      {"a": "hostile_mech_loyalist_02", "n": 6, "t": 12, "at": [(6, 3), (6, 5)], "tier": "A"},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_30": {
    "file": H,
    "note": "Two Fronts. The Bramble from the west, sector command's regulars from the east, and both keep coming: seven Bramble and five B-tier regulars at 1, Undertow under the middle at 2, Bramble and Sirenmaw at 4, four A-tier regulars at 5, six Bramble and three more regulars at 7, the Choir at 9. Neither side waits for the other. (Eight/six/six/eight put eleven mechs down a run and never won; six/four/four/six won 20/20 at six down; attrition fights cliff, and this sits on the edge on purpose.)",
    "waves": [
      {"a": "bloom_bramble", "n": 7, "t": 1, "at": [(0, 2), (0, 8)]},
      {"a": "hostile_mech_loyalist_01", "n": 2, "t": 1, "at": [(23, 2), (23, 8)], "tier": "B"},
      {"a": "hostile_mech_loyalist_03", "n": 2, "t": 1, "at": [(23, 2), (23, 8)], "tier": "B"},
      {"a": "hostile_mech_loyalist_02", "n": 1, "t": 1, "at": [(23, 2)], "tier": "B"},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(8, 4), (15, 4), (8, 6), (15, 6)], "burrowed": True},
      {"a": "bloom_bramble", "n": 5, "t": 4, "at": [(0, 2), (0, 8)]},
      {"a": "bloom_sirenmaw", "n": 3, "t": 4, "at": [(0, 2), (0, 8)]},
      {"a": "hostile_mech_loyalist_02", "n": 2, "t": 5, "at": [(23, 2), (23, 8)], "tier": "A"},
      {"a": "hostile_mech_loyalist_04", "n": 2, "t": 5, "at": [(23, 2), (23, 8)], "tier": "A"},
      {"a": "bloom_bramble", "n": 6, "t": 7, "at": [(0, 2), (0, 8)]},
      {"a": "hostile_mech_loyalist_01", "n": 2, "t": 7, "at": [(23, 2), (23, 8)], "tier": "A"},
      {"a": "hostile_mech_loyalist_03", "n": 1, "t": 7, "at": [(23, 8)], "tier": "A"},
      {"a": "bloom_choir", "n": 3, "t": 9, "at": [(0, 2), (0, 8)]},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_31": {
    "file": H,
    "note": "What the Program Costs. Six technicians, the Bramble already in the corridor: a pair mid-field at 1, Undertow at the corridor's edges at 2, three more at 3, three landing on the tree line at 5, Sirenmaw behind at 6, a last three at 8. Three of six have to make it. Turn limit 18 -> 13. (First cut lost four technicians by turn 6 in 18/20 runs; the Bramble reaches a fleeing technician in one move.)",
    "waves": [
      {"a": "bloom_bramble", "n": 2, "t": 1, "at": [(12, 1), (12, 8)]},
      {"a": "bloom_undertow", "n": 2, "t": 2, "at": [(7, 7), (17, 2)], "burrowed": True},
      {"a": "bloom_bramble", "n": 3, "t": 3, "at": [(12, 1), (12, 8)]},
      {"a": "bloom_bramble", "n": 3, "t": 5, "at": [(22, 1), (22, 8)]},
      {"a": "bloom_sirenmaw", "n": 2, "t": 6, "at": [(1, 1), (1, 8)]},
      {"a": "bloom_bramble", "n": 3, "t": 8, "at": [(12, 1), (12, 8)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'turnLimit': 13},
  },
  "HOUSE_AMARANTH_MISSION_32": {
    "file": H,
    "note": "Hold the Root. The Bramble knows what the dock is, and the squad now deploys on the dock's own west face instead of nine tiles away: drift from north and south at 1, Undertow under the dock approaches at 2, Bramble north and south at 3, a pack from the east at 4, Sirenmaw at 6, packs at 7, the Choir with the east pack at 10, and the last push at 13. Sixteen turns. (First cut: a turn-1 Bramble pack reached the dock in one move and the Root was dead by turn 5-7, 20/20.)",
    "waves": [
      {"a": "bloom_crawlmass", "n": 10, "t": 1, "at": [(11, 1), (11, 11)]},
      {"a": "bloom_undertow", "n": 4, "t": 2, "at": [(9, 4), (14, 4), (9, 9), (14, 9)], "burrowed": True},
      {"a": "bloom_bramble", "n": 6, "t": 3, "at": [(11, 1), (11, 11)]},
      {"a": "bloom_bramble", "n": 6, "t": 4, "at": [(22, 6), (22, 7)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 6, "at": [(11, 1), (11, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 7, "at": [(11, 1), (11, 11)]},
      {"a": "bloom_bramble", "n": 6, "t": 10, "at": [(22, 6), (22, 7)]},
      {"a": "bloom_choir", "n": 2, "t": 10, "at": [(22, 6)]},
      {"a": "bloom_bramble", "n": 8, "t": 13, "at": [(11, 1), (11, 11)]},
    ],
    "events": [],
    "bonus": None,
    "params": {'assetMaxHp': 400, 'assetName': 'Root'},
  },
  "HOUSE_AMARANTH_MISSION_33": {
    "file": H,
    "note": 'The Innermost Terrace. Five approaches, all Bramble: ten from the north at 1 with four Undertow under the perimeter, eight from the south at 3, eight from the east with Sirenmaw at 5, eight north at 7, eight south with the Choir and more Undertow at 9, eight east at 11, six north at 13, and six south with the Choir at 15 — the ones that have to be in the ring with you. Hold from 16 to 20.',
    "waves": [
      {"a": "bloom_bramble", "n": 10, "t": 1, "at": [(12, 1), (13, 1)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(11, 5), (14, 5), (11, 8), (14, 8)], "burrowed": True},
      {"a": "bloom_bramble", "n": 8, "t": 3, "at": [(12, 11), (13, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 5, "at": [(24, 6), (24, 7)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(24, 6), (24, 7)]},
      {"a": "bloom_bramble", "n": 8, "t": 7, "at": [(12, 1), (13, 1)]},
      {"a": "bloom_bramble", "n": 8, "t": 9, "at": [(12, 11), (13, 11)]},
      {"a": "bloom_choir", "n": 4, "t": 9, "at": [(12, 11), (13, 11)]},
      {"a": "bloom_undertow", "n": 2, "t": 9, "at": [(12, 6), (13, 7)], "burrowed": True},
      {"a": "bloom_bramble", "n": 8, "t": 11, "at": [(24, 6), (24, 7)]},
      {"a": "bloom_bramble", "n": 6, "t": 13, "at": [(12, 1), (13, 1)]},
      {"a": "bloom_bramble", "n": 6, "t": 15, "at": [(12, 11), (13, 11)]},
      {"a": "bloom_choir", "n": 2, "t": 15, "at": [(12, 1), (13, 1)]},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_34": {
    "file": H,
    "note": 'No Word From the Seal. Eight directions, all of them bad: sixteen Bramble from every seam at 1 with six Undertow under the ground around the pads, the Choir at 3, Bramble and Sirenmaw at 5, more Undertow at 7, fourteen Bramble at 8, the Choir at 10, Bramble and Sirenmaw at 11, Bramble at 13, and the Choir at 15. Sixteen turns.',
    "waves": [
      {"a": "bloom_bramble", "n": 16, "t": 1, "at": [(11, 1), (12, 1), (2, 2), (21, 2), (1, 6), (22, 6), (2, 10), (11, 11)]},
      {"a": "bloom_undertow", "n": 6, "t": 1, "at": [(8, 5), (15, 5), (8, 8), (15, 8), (11, 4), (12, 9)], "burrowed": True},
      {"a": "bloom_choir", "n": 6, "t": 3, "at": [(11, 1), (12, 11)]},
      {"a": "bloom_bramble", "n": 12, "t": 5, "at": [(2, 2), (21, 2), (2, 10), (21, 10)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(1, 6), (22, 6)]},
      {"a": "bloom_undertow", "n": 6, "t": 7, "at": [(8, 5), (15, 5), (8, 8), (15, 8), (11, 4), (12, 9)], "burrowed": True},
      {"a": "bloom_bramble", "n": 14, "t": 8, "at": [(11, 1), (12, 1), (11, 11), (12, 11)]},
      {"a": "bloom_choir", "n": 6, "t": 10, "at": [(1, 6), (22, 6)]},
      {"a": "bloom_bramble", "n": 10, "t": 11, "at": [(2, 2), (21, 2), (2, 10), (21, 10)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 11, "at": [(11, 1), (12, 11)]},
      {"a": "bloom_bramble", "n": 12, "t": 13, "at": [(1, 6), (22, 6), (11, 1), (12, 11)]},
      {"a": "bloom_choir", "n": 4, "t": 15, "at": [(2, 2), (21, 10)]},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_35": {
    "file": H,
    "note": "The Root Turns. It's directing, and the Bramble comes where it points: ten from the north at 1 with Undertow in the perimeter, ten from the south at 3, eight east with Sirenmaw at 5, eight north with the Choir at 7, eight south at 9, eight east with more Undertow at 11, six north with the Choir at 13, six south at 15 — those last are the ones in the ring with you. Hold from 16 to 20.",
    "waves": [
      {"a": "bloom_wellroot", "n": 1, "t": 1, "at": [(15, 6)]},
      {"a": "bloom_bramble", "n": 10, "t": 1, "at": [(11, 1), (12, 1)]},
      {"a": "bloom_undertow", "n": 4, "t": 1, "at": [(10, 5), (13, 5), (10, 8), (13, 8)], "burrowed": True},
      {"a": "bloom_bramble", "n": 10, "t": 3, "at": [(11, 11), (12, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 5, "at": [(22, 6), (22, 7)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 5, "at": [(22, 6), (22, 7)]},
      {"a": "bloom_bramble", "n": 8, "t": 7, "at": [(11, 1), (12, 1)]},
      {"a": "bloom_choir", "n": 4, "t": 7, "at": [(11, 1), (12, 1)]},
      {"a": "bloom_bramble", "n": 8, "t": 9, "at": [(11, 11), (12, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 11, "at": [(22, 6), (22, 7)]},
      {"a": "bloom_undertow", "n": 2, "t": 11, "at": [(10, 5), (13, 8)], "burrowed": True},
      {"a": "bloom_bramble", "n": 4, "t": 13, "at": [(11, 1), (12, 1)]},
      {"a": "bloom_choir", "n": 2, "t": 13, "at": [(11, 11), (12, 11)]},
      {"a": "bloom_bramble", "n": 4, "t": 15, "at": [(11, 11), (12, 11)]},
    ],
    "events": [],
    "bonus": None,
  },
  "HOUSE_AMARANTH_MISSION_36": {
    "file": H,
    "note": "The Stalling Season Ends. The whole bargain, one more time, with the Wellroot directing from beside the pads: twelve Bramble from every seam at 1 with eight Undertow under the pads, the Choir at 3, Bramble and Sirenmaw at 4, Bramble at 6, the Choir at 7, Bramble and Sirenmaw at 9, Bramble and Undertow at 11, Bramble and the Choir at 13, Bramble and Sirenmaw at 15, and the last of it at 17. Eighteen turns. Hold until the doctrine closes.",
    "waves": [
      {"a": "bloom_wellroot", "n": 1, "t": 1, "at": [(17, 6)]},
      {"a": "bloom_bramble", "n": 12, "t": 1, "at": [(12, 1), (13, 1), (12, 11), (13, 11), (2, 2), (23, 2), (2, 10), (23, 10)]},
      {"a": "bloom_undertow", "n": 8, "t": 1, "at": [(9, 5), (16, 5), (9, 8), (16, 8), (12, 4), (13, 9), (8, 6), (17, 8)], "burrowed": True},
      {"a": "bloom_choir", "n": 6, "t": 3, "at": [(12, 1), (13, 11)]},
      {"a": "bloom_bramble", "n": 10, "t": 4, "at": [(1, 6), (24, 6), (2, 2), (23, 10)]},
      {"a": "bloom_sirenmaw", "n": 6, "t": 4, "at": [(1, 6), (24, 6)]},
      {"a": "bloom_bramble", "n": 8, "t": 6, "at": [(12, 1), (13, 1), (12, 11), (13, 11)]},
      {"a": "bloom_choir", "n": 6, "t": 7, "at": [(1, 6), (24, 6)]},
      {"a": "bloom_bramble", "n": 12, "t": 9, "at": [(2, 2), (23, 2), (2, 10), (23, 10)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 9, "at": [(12, 1), (13, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 11, "at": [(1, 6), (24, 6)]},
      {"a": "bloom_undertow", "n": 4, "t": 11, "at": [(9, 5), (16, 5), (9, 8), (16, 8)], "burrowed": True},
      {"a": "bloom_bramble", "n": 10, "t": 13, "at": [(12, 1), (13, 1), (12, 11), (13, 11)]},
      {"a": "bloom_choir", "n": 6, "t": 13, "at": [(2, 2), (23, 10)]},
      {"a": "bloom_bramble", "n": 12, "t": 15, "at": [(1, 6), (24, 6), (2, 2), (23, 2)]},
      {"a": "bloom_sirenmaw", "n": 4, "t": 15, "at": [(12, 1), (13, 11)]},
      {"a": "bloom_bramble", "n": 8, "t": 17, "at": [(12, 1), (13, 1), (12, 11), (13, 11)]},
    ],
    "events": [],
    "bonus": None,
  },
}
