// src/data/mapsAmaranth.ts
// Maps for "The Amaranth Reckoning" — Act I: The Fallow Line (independent,
// non-canon campaign concept; see the project's
// Bloom_Wars_Independent_Campaign_The_Amaranth_Reckoning.md /
// design/Bloom_Wars_The_Amaranth_Reckoning.docx). Same engine, same tile
// vocabulary, a separate roster and mission set from the Team One slice in
// data/campaign.ts — kept in its own files end to end so the two campaigns
// never collide (Section 1 of that doc: "built to run in parallel... no
// shared characters, no shared plot beats").
//
// Grids were authored as ASCII (same legend as maps_output.txt) and run
// through a small offline validator before transcription here — checked
// rectangular, known tile vocabulary only, and BFS-reachable from every
// deploy pad to every spawn/hold tile (the same two checks the project's
// maps.py performs on the original four maps). Hand-transcribed from that
// validated ASCII, not regenerated by maps.py itself, since these missions
// don't exist in Data Pack §10 — flagging that per this repo's own "don't
// hand-edit the TypeScript grids" caution in README.md, which is about
// drift from a *checked-in* ASCII source; there isn't one for these four
// yet if anyone wants to add one under design/.
import type { MapDefinition, TileType } from "./types";
import { makeMap } from "./maps";

// ---- Mission 1: Muster — tutorial, open border-post ground ----
const MUSTER_TILES: TileType[][] = [
  ["ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge"],
  ["ridge", "scrub", "scrub", "plain", "plain", "structure", "structure", "plain", "plain", "plain", "scrub", "scrub", "scrub", "ridge"],
  ["scrub", "scrub", "plain", "plain", "plain", "structure", "structure", "plain", "plain", "plain", "plain", "scrub", "scrub", "scrub"],
  ["deploy", "plain", "plain", "road", "road", "road", "road", "road", "road", "road", "plain", "plain", "scrub", "scrub"],
  ["deploy", "deploy", "plain", "road", "road", "plain", "plain", "plain", "plain", "road", "road", "plain", "scrub", "spawn"],
  ["deploy", "plain", "plain", "road", "road", "plain", "rubble", "rubble", "plain", "road", "road", "plain", "scrub", "spawn"],
  ["deploy", "deploy", "plain", "road", "road", "plain", "plain", "plain", "plain", "road", "road", "plain", "plain", "plain"],
  ["scrub", "scrub", "plain", "plain", "plain", "structure", "structure", "plain", "plain", "plain", "plain", "scrub", "scrub", "scrub"],
  ["ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge"],
];

// ---- Mission 2: Wire and Mud — single-doorway hold zone ----
// The listening post's hold room sits at cols 6-10 / rows 2-7. The west
// wall (col 6) is solid on every interior row except row 4 — the one
// doorway, and the whole point of the mission (Bosk plants himself there).
// The east wall (col 10) never opens, so hostiles spawning east have to
// walk all the way around the building (rows 0-1 or 8-9) to reach that same
// single gap — both sides funnel through one tile.
const WIRE_AND_MUD_TILES: TileType[][] = [
  ["ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge"],
  ["ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge"],
  ["scrub", "scrub", "plain", "plain", "plain", "plain", "wall", "wall", "wall", "wall", "wall", "plain", "plain", "plain", "scrub", "scrub"],
  ["deploy", "plain", "plain", "plain", "plain", "plain", "wall", "hold", "hold", "hold", "wall", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "deploy", "plain", "plain", "plain", "plain", "plain", "hold", "hold", "hold", "wall", "spawn", "plain", "plain", "plain", "plain"],
  ["deploy", "plain", "plain", "plain", "plain", "plain", "wall", "hold", "hold", "hold", "wall", "spawn", "plain", "plain", "plain", "plain"],
  ["deploy", "deploy", "plain", "plain", "plain", "plain", "wall", "hold", "hold", "hold", "wall", "plain", "plain", "plain", "plain", "plain"],
  ["scrub", "scrub", "plain", "plain", "plain", "plain", "wall", "wall", "wall", "wall", "wall", "plain", "plain", "plain", "scrub", "scrub"],
  ["ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge"],
  ["ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge"],
];

// ---- Mission 3: The Low Ground — bloom mat flooded the terraces overnight ----
const THE_LOW_GROUND_TILES: TileType[][] = [
  ["ridge", "ridge", "ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge", "ridge"],
  ["ridge", "ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge"],
  ["deploy", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "scrub"],
  ["deploy", "deploy", "plain", "plain", "bloom_mat", "bloom_mat", "plain", "plain", "plain", "bloom_mat", "bloom_mat", "plain", "plain", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "deploy", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "plain"],
  ["plain", "plain", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "plain"],
  ["plain", "plain", "plain", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "plain", "plain"],
  ["scrub", "scrub", "plain", "plain", "plain", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "bloom_mat", "plain", "plain", "plain", "plain", "scrub", "scrub", "plain"],
  ["scrub", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "spawn"],
  ["ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "spawn"],
];

// ---- Mission 4: Tunnel Rats — first burrower contact ----
// A rubble-walled listening-post ruin. The two burrowed Undertow spawn deep
// inside (row 4); the rubble ring costs extra move but is never a hard
// wall, so a player unit can push straight through it instead of only
// using the gaps at top/bottom.
const TUNNEL_RATS_TILES: TileType[][] = [
  ["ridge", "ridge", "ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge", "ridge"],
  ["ridge", "ridge", "scrub", "scrub", "scrub", "rubble", "rubble", "rubble", "rubble", "scrub", "scrub", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge"],
  ["deploy", "scrub", "scrub", "rubble", "rubble", "plain", "plain", "plain", "plain", "rubble", "rubble", "plain", "plain", "scrub", "scrub", "plain", "plain", "plain"],
  ["deploy", "deploy", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "plain", "plain", "plain", "plain", "rubble", "plain", "plain", "spawn", "spawn", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "deploy", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "spawn"],
  ["deploy", "plain", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain", "plain", "rubble", "plain", "plain", "plain", "plain", "plain"],
  ["deploy", "scrub", "scrub", "rubble", "rubble", "plain", "plain", "plain", "plain", "rubble", "rubble", "plain", "plain", "scrub", "scrub", "plain", "plain", "plain"],
  ["ridge", "ridge", "scrub", "scrub", "scrub", "rubble", "rubble", "rubble", "rubble", "scrub", "scrub", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge"],
  ["ridge", "ridge", "ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge", "ridge"],
  ["ridge", "ridge", "ridge", "ridge", "ridge", "scrub", "scrub", "plain", "plain", "plain", "plain", "scrub", "scrub", "ridge", "ridge", "ridge", "ridge", "ridge"],
];

export const map_amaranth_muster = makeMap("map_amaranth_muster", "Muster — Thistledown Watch", 14, 9, MUSTER_TILES);
export const map_amaranth_wire_and_mud = makeMap("map_amaranth_wire_and_mud", "Wire and Mud — the Listening Post", 16, 10, WIRE_AND_MUD_TILES);
export const map_amaranth_the_low_ground = makeMap("map_amaranth_the_low_ground", "The Low Ground", 18, 11, THE_LOW_GROUND_TILES);
export const map_amaranth_tunnel_rats = makeMap("map_amaranth_tunnel_rats", "Tunnel Rats", 18, 11, TUNNEL_RATS_TILES);

export const MAPS_AMARANTH: Record<string, MapDefinition> = {
  map_amaranth_muster,
  map_amaranth_wire_and_mud,
  map_amaranth_the_low_ground,
  map_amaranth_tunnel_rats,
};
